<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue';
import { onBeforeRouteLeave, useRoute, useRouter } from 'vue-router';
import { ElMessage, ElMessageBox } from 'element-plus';
import { request } from '../api/request';
import WorkOrderCreateDialog from '../components/WorkOrderCreateDialog.vue';
import { useAuthStore } from '../stores/auth';
import type { Device, PageResult, UserSummary } from '../types/device';
import type { Defect, DiagnosisView, WorkflowTrace, WorkOrder } from '../types/maintenance';
import { displayValue } from '../utils/display';
import { notificationSocket, type ConnectionState, type NotificationMessage } from '../services/notificationSocket';
const route=useRoute(),router=useRouter(),auth=useAuthStore(),view=ref<DiagnosisView>(),trace=ref<WorkflowTrace[]>([]),device=ref<Device>(),defect=ref<Defect>(),workOrder=ref<WorkOrder>(),confirmer=ref('未确认'),loading=ref(false),errorMessage=ref(''),busy=ref(''),confirmVisible=ref(false),orderVisible=ref(false),confirmForm=reactive({decision:'CONFIRMED',comment:''}),snapshot=ref(''),connectionState=ref<ConnectionState>('disconnected');
let unsubscribeMessage:undefined|(()=>void),unsubscribeState:undefined|(()=>void),refreshTimer:number|undefined,lastConnection:ConnectionState='disconnected';
const diagnosis=computed(()=>view.value?.diagnosis),deviceLabel=computed(()=>device.value?`${device.value.deviceName}（${device.value.deviceCode}）`:'设备信息加载中'),canDecide=computed(()=>auth.can('ai:confirm')&&diagnosis.value?.diagnosisStatus==='SUCCEEDED'&&diagnosis.value?.confirmationStatus==='PENDING'),canBind=computed(()=>auth.can('maintenance:defect:process')&&defect.value?.status==='CONFIRMED'&&diagnosis.value?.diagnosisStatus==='SUCCEEDED'&&diagnosis.value?.confirmationStatus==='CONFIRMED'&&defect.value.aiDiagnosisId!==diagnosis.value.id),canCreate=computed(()=>auth.can('maintenance:workorder:create')&&diagnosis.value?.diagnosisStatus==='SUCCEEDED'&&diagnosis.value?.confirmationStatus==='CONFIRMED'&&Boolean(view.value?.workOrderDraft)&&!workOrder.value&&(!defect.value||defect.value.aiDiagnosisId===diagnosis.value.id)),dirty=computed(()=>confirmVisible.value&&JSON.stringify(confirmForm)!==snapshot.value),factsText=computed(()=>JSON.stringify(diagnosis.value?.contextSnapshot??{},null,2)),missingItems=computed(()=>{const v=diagnosis.value?.contextSnapshot?.missingItems;return Array.isArray(v)?v.map(String):[];});
const dateTime=(v:string|null|undefined)=>v?v.replace('T',' ').slice(0,19):'-';
const duration=(v:number|null)=>v==null?'-':v<1000?`${v} ms`:`${(v/1000).toFixed(1)} s`;
function scheduleRefresh(){if(refreshTimer)window.clearTimeout(refreshTimer);if(diagnosis.value?.diagnosisStatus==='RUNNING'||diagnosis.value?.diagnosisStatus==='PENDING')refreshTimer=window.setTimeout(()=>void load(true),5000);}
async function load(background=false){if(loading.value)return;if(!background)loading.value=true;errorMessage.value='';try{const id=String(route.params.id);const [v,t]=await Promise.all([request.get<never,DiagnosisView>(`/api/ai/diagnoses/${id}`),request.get<never,WorkflowTrace[]>(`/api/ai/diagnoses/${id}/workflow`)]);view.value=v;trace.value=t??[];const d=v.diagnosis,jobs:Promise<unknown>[]=[request.get<never,Device>(`/api/device/devices/${d.deviceId}`).then(x=>device.value=x)];if(auth.can('maintenance:view')){if(d.triggerType!=='MANUAL'&&d.triggerId)jobs.push(request.get<never,PageResult<Defect>>('/api/maintenance/defects',{params:{sourceType:d.triggerType,sourceId:d.triggerId,pageNum:1,pageSize:2}}).then(x=>defect.value=x.records?.[0]));else defect.value=undefined;jobs.push(request.get<never,PageResult<WorkOrder>>('/api/maintenance/work-orders',{params:{aiDiagnosisId:d.id,pageNum:1,pageSize:2}}).then(x=>workOrder.value=x.records?.[0]));}if(d.confirmedBy&&auth.can('system:user:view'))jobs.push(request.get<never,UserSummary>(`/api/auth/users/${d.confirmedBy}`,{silentStatuses:[404]}).then(u=>confirmer.value=u.realName?`${u.realName}（${u.username}）`:u.username).catch((e:any)=>confirmer.value=e.response?.status===404?'原确认人（账号已删除）':'人员信息暂不可用'));await Promise.allSettled(jobs);}catch{errorMessage.value='AI 诊断详情加载失败，可能无权访问或服务暂不可用。';}finally{loading.value=false;scheduleRefresh();}}
function onWorkflowEvent(message:NotificationMessage){if(message.notificationType==='AI_WORKFLOW'&&message.bizType==='AI_DIAGNOSIS'&&message.bizId===String(route.params.id))void load(true);}
function openDecision(decision:'CONFIRMED'|'REJECTED'){Object.assign(confirmForm,{decision,comment:''});snapshot.value=JSON.stringify(confirmForm);confirmVisible.value=true}
async function closeDecision(){if(dirty.value){try{await ElMessageBox.confirm('确认意见尚未提交，确定放弃吗？','放弃确认',{type:'warning'});}catch{return}}confirmVisible.value=false}
async function decide(){if(!diagnosis.value)return;if(confirmForm.decision==='REJECTED'&&!confirmForm.comment.trim())return void ElMessage.warning('拒绝时必须填写原因');busy.value='decision';try{await request.post(`/api/ai/diagnoses/${diagnosis.value.id}/${confirmForm.decision==='CONFIRMED'?'confirm':'reject'}`,{comment:confirmForm.comment});confirmVisible.value=false;ElMessage.success(confirmForm.decision==='CONFIRMED'?'诊断已确认':'诊断已拒绝');await load();}catch(e:any){if(e.response?.status===409)await load();}finally{busy.value='';}}
async function bind(){if(!diagnosis.value||!defect.value)return;busy.value='bind';try{await request.put(`/api/maintenance/defects/${defect.value.id}/ai-diagnosis`,{aiDiagnosisId:diagnosis.value.id});ElMessage.success('诊断已显式绑定到缺陷');await load();}finally{busy.value='';}}
function created(o:WorkOrder){workOrder.value=o;void router.push(`/maintenance/work-orders/${o.id}`)}
onBeforeRouteLeave(async()=>{if(!dirty.value)return true;try{await ElMessageBox.confirm('确认意见尚未提交，确定离开吗？','离开页面',{type:'warning'});return true}catch{return false}});onMounted(()=>{unsubscribeMessage=notificationSocket.subscribe(onWorkflowEvent);unsubscribeState=notificationSocket.subscribeState(state=>{connectionState.value=state;if(state==='connected'&&lastConnection==='disconnected')void load(true);lastConnection=state;});void load();});onBeforeUnmount(()=>{unsubscribeMessage?.();unsubscribeState?.();if(refreshTimer)window.clearTimeout(refreshTimer);});
</script>
<template><section class="detail-page"><div class="page-head"><div><el-button link @click="router.push('/ai/diagnoses')">← 返回诊断列表</el-button><h1>AI 诊断详情</h1><p>结构化展示五节点诊断结果；AI 只提供辅助意见，确认和落单均需人工操作。</p></div><div v-if="diagnosis" class="head-actions"><el-button v-if="canDecide" type="primary" @click="openDecision('CONFIRMED')">确认诊断</el-button><el-button v-if="canDecide" type="danger" plain @click="openDecision('REJECTED')">拒绝诊断</el-button><el-button v-if="canBind" type="primary" plain :loading="busy==='bind'" @click="bind">绑定到缺陷</el-button><el-button v-if="canCreate" type="success" @click="orderVisible=true">根据草案创建工单</el-button></div></div>
<el-alert v-if="errorMessage" :title="errorMessage" type="error" show-icon :closable="false"><template #default><el-button link @click="load()">重新加载</el-button></template></el-alert><template v-else-if="diagnosis&&view"><el-alert v-if="diagnosis.diagnosisStatus==='FAILED'" :title="`诊断失败：${diagnosis.errorMessage||'模型服务未返回有效结果'}`" type="error" show-icon :closable="false"/><el-alert v-else-if="diagnosis.diagnosisStatus==='RUNNING'||diagnosis.diagnosisStatus==='PENDING'" :title="connectionState==='connected'?'诊断正在执行，页面将通过 WebSocket 实时恢复状态。':'实时连接已断开，后端诊断仍会继续；页面将通过 REST 定期恢复真实状态。'" :type="connectionState==='connected'?'info':'warning'" show-icon :closable="false"/><el-card v-loading="loading" shadow="never"><template #header><strong>诊断概况</strong></template><el-descriptions :column="3" border><el-descriptions-item label="诊断编号">{{diagnosis.diagnosisCode}}</el-descriptions-item><el-descriptions-item label="诊断状态"><el-tag :type="diagnosis.diagnosisStatus==='FAILED'?'danger':diagnosis.diagnosisStatus==='SUCCEEDED'?'success':'info'">{{displayValue(diagnosis.diagnosisStatus)}}</el-tag></el-descriptions-item><el-descriptions-item label="人工确认"><el-tag>{{displayValue(diagnosis.confirmationStatus)}}</el-tag></el-descriptions-item><el-descriptions-item label="设备">{{deviceLabel}} <el-button link @click="router.push(`/devices/${diagnosis.deviceId}`)">查看设备</el-button></el-descriptions-item><el-descriptions-item label="触发来源">{{displayValue(diagnosis.triggerType)}} <el-button v-if="diagnosis.triggerType==='INSPECTION_ABNORMAL'&&diagnosis.triggerId" link @click="router.push(`/inspection/abnormals/${diagnosis.triggerId}`)">查看异常</el-button></el-descriptions-item><el-descriptions-item label="风险等级"><el-tag :type="diagnosis.riskLevel==='HIGH'||diagnosis.riskLevel==='CRITICAL'?'danger':'warning'">{{displayValue(diagnosis.riskLevel)}}</el-tag></el-descriptions-item><el-descriptions-item label="AI 诊断摘要" :span="3">{{diagnosis.abnormalSummary||'-'}}</el-descriptions-item><el-descriptions-item label="用户补充" :span="3">{{diagnosis.userDescription||'-'}}</el-descriptions-item><el-descriptions-item label="模型 / 提示词">{{diagnosis.modelName||'-'}} / {{diagnosis.promptVersion||'-'}}</el-descriptions-item><el-descriptions-item label="诊断时间">{{dateTime(diagnosis.createdAt)}}</el-descriptions-item><el-descriptions-item label="确认人员">{{diagnosis.confirmedBy?confirmer:'未确认'}}</el-descriptions-item><el-descriptions-item v-if="diagnosis.confirmationComment" label="确认意见" :span="3">{{diagnosis.confirmationComment}}</el-descriptions-item></el-descriptions></el-card>
<el-card shadow="never"><template #header><strong>固定五节点 Workflow</strong></template><el-steps direction="vertical" :active="trace.filter(x=>x.status==='SUCCEEDED').length" finish-status="success"><el-step v-for="x in trace" :key="x.id" :title="x.nodeName||displayValue(x.nodeCode)" :status="x.status==='FAILED'?'error':x.status==='SUCCEEDED'?'success':x.status==='RUNNING'?'process':'wait'"><template #description><div>{{x.nodeCode}} · {{displayValue(x.status)}} · 耗时 {{duration(x.duration)}}</div><div>{{x.message}}</div><div v-if="x.errorMessage" class="error-text">{{x.errorMessage}}</div></template></el-step></el-steps></el-card>
<el-card shadow="never"><template #header><strong>业务事实（系统上下文快照）</strong></template><el-alert v-if="missingItems.length" :title="`部分上下文缺失：${missingItems.join('、')}`" type="warning" show-icon :closable="false"/><pre class="facts">{{factsText}}</pre></el-card>
<el-card shadow="never"><template #header><strong>风险判断（AI 辅助，不改变设备正式状态）</strong></template><el-descriptions :column="1" border><el-descriptions-item label="风险等级"><el-tag :type="diagnosis.riskLevel==='HIGH'||diagnosis.riskLevel==='CRITICAL'?'danger':'warning'">{{displayValue(diagnosis.riskLevel)}}</el-tag></el-descriptions-item><el-descriptions-item label="风险摘要">{{diagnosis.abnormalSummary||'-'}}</el-descriptions-item><el-descriptions-item label="判断依据"><ul v-if="view.possibleCauses.length"><li v-for="x in view.possibleCauses" :key="x">{{x}}</li></ul><span v-else>-</span></el-descriptions-item></el-descriptions></el-card>
<el-row :gutter="16"><el-col :xs="24" :lg="12"><el-card class="full-card" shadow="never"><template #header><strong>AI 诊断：可能原因</strong></template><ol v-if="view.possibleCauses.length"><li v-for="x in view.possibleCauses" :key="x">{{x}}</li></ol><el-empty v-else description="无原因建议"/></el-card></el-col><el-col :xs="24" :lg="12"><el-card class="full-card" shadow="never"><template #header><strong>AI 建议：排查步骤</strong></template><ol v-if="view.investigationSteps.length"><li v-for="x in view.investigationSteps" :key="x">{{x}}</li></ol><el-empty v-else description="无排查步骤"/></el-card></el-col></el-row>
<el-card shadow="never"><template #header><strong>维修建议与安全提示</strong></template><el-descriptions :column="1" border><el-descriptions-item label="维修建议">{{diagnosis.maintenanceAdvice||'-'}}</el-descriptions-item><el-descriptions-item label="安全提示">{{diagnosis.safetyNotice||'-'}}</el-descriptions-item></el-descriptions></el-card>
<el-card shadow="never"><template #header><strong>工单草案（不会自动创建）</strong></template><el-descriptions v-if="view.workOrderDraft" :column="2" border><el-descriptions-item label="标题">{{view.workOrderDraft.title||'-'}}</el-descriptions-item><el-descriptions-item label="建议优先级">{{displayValue(view.workOrderDraft.priority)}}</el-descriptions-item><el-descriptions-item label="描述" :span="2">{{view.workOrderDraft.description||'-'}}</el-descriptions-item><el-descriptions-item label="维修建议" :span="2">{{view.workOrderDraft.maintenanceAdvice||'-'}}</el-descriptions-item><el-descriptions-item label="安全提示" :span="2">{{view.workOrderDraft.safetyNotice||'-'}}</el-descriptions-item></el-descriptions><el-empty v-else description="工作流尚未生成工单草稿"/><el-alert v-if="diagnosis.confirmationStatus==='REJECTED'" title="该诊断已被拒绝，不能据此创建正式工单。" type="warning" show-icon :closable="false"/><el-alert v-else-if="defect&&diagnosis.confirmationStatus==='CONFIRMED'&&defect.aiDiagnosisId!==diagnosis.id" title="请先把已确认诊断显式绑定到来源缺陷，再创建正式工单。" type="info" show-icon :closable="false"/></el-card>
<el-card shadow="never"><template #header><strong>人工结论</strong></template><el-descriptions :column="2" border><el-descriptions-item label="确认状态"><el-tag>{{displayValue(diagnosis.confirmationStatus)}}</el-tag></el-descriptions-item><el-descriptions-item label="处理时间">{{dateTime(diagnosis.confirmedAt)}}</el-descriptions-item><el-descriptions-item label="处理人">{{diagnosis.confirmedBy?confirmer:'待人工处理'}}</el-descriptions-item><el-descriptions-item label="处理意见">{{diagnosis.confirmationComment||'-'}}</el-descriptions-item></el-descriptions><el-alert v-if="diagnosis.confirmationStatus==='PENDING'" title="AI 不会自动确认；具备权限的人员必须显式确认或拒绝。" type="info" show-icon :closable="false"/></el-card>
<el-row v-if="auth.can('maintenance:view')" :gutter="16"><el-col :xs="24" :lg="12"><el-card class="full-card" shadow="never"><template #header><strong>关联缺陷</strong></template><template v-if="defect"><p>{{defect.defectCode}} · {{defect.title}}</p><el-tag>{{displayValue(defect.status)}}</el-tag><el-tag v-if="defect.aiDiagnosisId===diagnosis.id" type="success">已绑定本诊断</el-tag><el-button link @click="router.push(`/maintenance/defects/${defect.id}`)">查看缺陷</el-button></template><el-empty v-else description="该诊断没有来源缺陷"/></el-card></el-col><el-col :xs="24" :lg="12"><el-card class="full-card" shadow="never"><template #header><strong>关联工单</strong></template><template v-if="workOrder"><p>{{workOrder.workOrderCode}} · {{workOrder.title}}</p><el-tag>{{displayValue(workOrder.status)}}</el-tag><el-button link @click="router.push(`/maintenance/work-orders/${workOrder.id}`)">查看工单</el-button></template><el-empty v-else description="尚未创建正式工单"/></el-card></el-col></el-row>
</template>
<el-dialog v-model="confirmVisible" :title="confirmForm.decision==='CONFIRMED'?'确认 AI 诊断':'拒绝 AI 诊断'" width="580px" :close-on-click-modal="false" :before-close="closeDecision"><el-alert :title="confirmForm.decision==='CONFIRMED'?'确认后仍需显式绑定缺陷并人工创建工单。':'拒绝后不能根据该诊断创建正式 AI 关联工单。'" :type="confirmForm.decision==='CONFIRMED'?'info':'warning'" show-icon :closable="false"/><el-form label-width="90px" class="dialog-form"><el-form-item label="处理意见" :required="confirmForm.decision==='REJECTED'"><el-input v-model="confirmForm.comment" type="textarea" :rows="4" :placeholder="confirmForm.decision==='REJECTED'?'请填写拒绝原因':'可填写确认依据'"/></el-form-item></el-form><template #footer><el-button @click="closeDecision">取消</el-button><el-button :type="confirmForm.decision==='CONFIRMED'?'primary':'danger'" :loading="busy==='decision'" @click="decide">提交决定</el-button></template></el-dialog>
<WorkOrderCreateDialog v-if="diagnosis" v-model:visible="orderVisible" :device-id="diagnosis.deviceId" :device-label="deviceLabel" :defect-id="defect?.id" :ai-diagnosis-id="diagnosis.id" :draft="view?.workOrderDraft" @created="created"/>
</section></template>
<style scoped>.detail-page{display:flex;flex-direction:column;gap:16px}.head-actions{display:flex;gap:10px;flex-wrap:wrap}.full-card{height:100%}.full-card .el-tag,.full-card .el-button{margin-right:8px}.full-card li{margin-bottom:10px;line-height:1.55}.dialog-form{margin-top:18px}.error-text{color:var(--el-color-danger)}.facts{max-height:280px;overflow:auto;margin:12px 0 0;padding:14px;border-radius:6px;background:var(--el-fill-color-light);white-space:pre-wrap;word-break:break-word;font-size:12px}</style>
