<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { ElMessage, ElMessageBox } from 'element-plus';
import { request } from '../api/request';
import { useAuthStore } from '../stores/auth';
import type { Device, PageResult } from '../types/device';
import type { Diagnosis, DiagnosisView, WorkOrder } from '../types/maintenance';
import { displayValue } from '../utils/display';
import { notificationSocket, type ConnectionState, type NotificationMessage } from '../services/notificationSocket';
const route=useRoute(),router=useRouter(),auth=useAuthStore(),rows=ref<Diagnosis[]>([]),total=ref(0),page=ref(1),loading=ref(false),errorMessage=ref(''),deviceOptions=ref<Device[]>([]),deviceNames=reactive<Record<string,string>>({}),workOrders=reactive<Record<string,WorkOrder|null>>({}),createVisible=ref(false),diagnosing=ref(false),connectionState=ref<ConnectionState>('disconnected'),progressMessage=ref('');
let unsubscribeMessage:undefined|(()=>void),unsubscribeState:undefined|(()=>void);
const pageSize=20,filters=reactive({triggerType:String(route.query.triggerType||''),triggerId:String(route.query.triggerId||''),deviceId:String(route.query.deviceId||''),diagnosisStatus:'',riskLevel:'',confirmationStatus:''}),form=reactive({deviceId:'',abnormalSummary:'',userDescription:''}),snapshot=ref('');
const linkedContext=computed(()=>Boolean(filters.triggerId)),canManual=computed(()=>auth.can('ai:diagnosis')&&!auth.roles.includes('INSPECTOR'));
const overview=reactive<{running:number|null;review:number|null;highRisk:number|null;confirmed:number|null}>({running:null,review:null,highRisk:null,confirmed:null});
const dateTime=(v:string)=>v?v.replace('T',' ').slice(0,19):'-',deviceLabel=(d:Device)=>`${d.deviceName}（${d.deviceCode}）`;
const diagnosisLabel=(v:string)=>({PENDING:'等待分析',RUNNING:'智能分析中',SUCCEEDED:'诊断完成',FAILED:'诊断未完成'} as Record<string,string>)[v]||displayValue(v);
const confirmationLabel=(v:string)=>({PENDING:'待审核',CONFIRMED:'已确认',REJECTED:'已拒绝'} as Record<string,string>)[v]||displayValue(v);
const workflowLabel=(v:string)=>({LOAD_CONTEXT:'数据汇聚',ANALYZE_WITH_DEEPSEEK:'AI 智能研判',RISK_CHECK:'风险校验',GENERATE_ADVICE:'处置方案',PREPARE_WORK_ORDER_DRAFT:'工单草案'} as Record<string,string>)[v]||'';
async function searchDevices(keyword=''){const p=await request.get<never,PageResult<Device>>('/api/device/devices',{params:{pageNum:1,pageSize:20,keyword:keyword||undefined}});deviceOptions.value=p.records??[];deviceOptions.value.forEach(d=>deviceNames[d.id]=deviceLabel(d));}
async function resolveDevices(data:Diagnosis[]){await Promise.allSettled([...new Set(data.map(x=>x.deviceId))].filter(id=>!deviceNames[id]).map(async id=>{const d=await request.get<never,Device>(`/api/device/devices/${id}`,{silentStatuses:[404]});deviceNames[id]=deviceLabel(d);}));}
async function resolveWorkOrders(data:Diagnosis[]){if(!auth.can('maintenance:view'))return;await Promise.allSettled(data.filter(x=>workOrders[x.id]===undefined).map(async diagnosis=>{const p=await request.get<never,PageResult<WorkOrder>>('/api/maintenance/work-orders',{params:{aiDiagnosisId:diagnosis.id,pageNum:1,pageSize:1}});workOrders[diagnosis.id]=p.records?.[0]??null;}));}
async function loadOverview(){
  const query=(params:Record<string,string>)=>request.get<never,PageResult<Diagnosis>>('/api/ai/diagnoses',{params:{...params,pageNum:1,pageSize:1},silentGlobalError:true});
  const results=await Promise.allSettled([query({diagnosisStatus:'RUNNING'}),query({diagnosisStatus:'SUCCEEDED',confirmationStatus:'PENDING'}),query({riskLevel:'HIGH'}),query({riskLevel:'CRITICAL'}),query({diagnosisStatus:'SUCCEEDED',confirmationStatus:'CONFIRMED'})]);
  overview.running=results[0].status==='fulfilled'?results[0].value.total:null;
  overview.review=results[1].status==='fulfilled'?results[1].value.total:null;
  overview.highRisk=results[2].status==='fulfilled'&&results[3].status==='fulfilled'?results[2].value.total+results[3].value.total:null;
  overview.confirmed=results[4].status==='fulfilled'?results[4].value.total:null;
}
async function load(){loading.value=true;errorMessage.value='';try{const p=await request.get<never,PageResult<Diagnosis>>('/api/ai/diagnoses',{params:{pageNum:page.value,pageSize,...Object.fromEntries(Object.entries(filters).map(([k,v])=>[k,v||undefined]))}});rows.value=p.records??[];total.value=p.total??0;await Promise.all([resolveDevices(rows.value),resolveWorkOrders(rows.value)]);}catch{errorMessage.value='AI 诊断列表加载失败，请稍后重试。';}finally{loading.value=false;}}
function search(){page.value=1;void load()}function reset(){Object.assign(filters,{triggerType:'',triggerId:'',deviceId:'',diagnosisStatus:'',riskLevel:'',confirmationStatus:''});void router.replace({path:route.path});search()}
function openCreate(){Object.assign(form,{deviceId:'',abnormalSummary:'',userDescription:''});snapshot.value=JSON.stringify(form);createVisible.value=true;void searchDevices()}
async function closeCreate(){if(JSON.stringify(form)!==snapshot.value){try{await ElMessageBox.confirm('诊断描述尚未提交，确定放弃吗？','放弃诊断',{type:'warning'});}catch{return}}createVisible.value=false}
function onWorkflowEvent(message:NotificationMessage){if(message.notificationType!=='AI_WORKFLOW'||message.bizType!=='AI_DIAGNOSIS'||!message.bizId)return;void loadOverview();if(!diagnosing.value)return;try{const event=JSON.parse(message.content) as {nodeCode?:string;nodeStatus?:string;message?:string};progressMessage.value=[event.nodeCode?workflowLabel(event.nodeCode):'',event.message||''].filter(Boolean).join(' · ');}catch{progressMessage.value='诊断状态已更新';}ElMessage.success('诊断任务已启动');void router.push(`/ai/diagnoses/${message.bizId}`);}
async function create(){if(!form.deviceId)return void ElMessage.warning('请选择诊断设备');if(!form.abnormalSummary.trim())return void ElMessage.warning('请填写异常摘要');diagnosing.value=true;progressMessage.value='正在创建诊断任务';try{const v=await request.post<never,DiagnosisView>('/api/ai/diagnoses',{triggerType:'MANUAL',triggerId:null,...form});createVisible.value=false;ElMessage.success(v.diagnosis.diagnosisStatus==='SUCCEEDED'?'诊断已完成，请进行人工确认':'诊断执行结束，请查看详情');await router.push(`/ai/diagnoses/${v.diagnosis.id}`);}catch(e:any){if(!e.response)ElMessage.warning('连接已中断，诊断可能仍在执行，请刷新诊断列表确认真实状态。');}finally{diagnosing.value=false;}}
onMounted(()=>{unsubscribeMessage=notificationSocket.subscribe(onWorkflowEvent);unsubscribeState=notificationSocket.subscribeState(state=>connectionState.value=state);void searchDevices();void load();void loadOverview()});
onBeforeUnmount(()=>{unsubscribeMessage?.();unsubscribeState?.();});
</script>
<template><section class="business-page"><div class="page-head"><div><h1>智能诊断中心</h1><p>汇聚设备与运维上下文，形成可审核、可追溯的智能诊断建议。</p></div><el-button v-if="canManual" type="primary" @click="openCreate">发起智能诊断</el-button></div>
<section class="ai-overview"><div class="overview-title"><span class="overview-orb">AI</span><div><strong>智能任务态势</strong><small>数据来自当前诊断记录</small></div></div><article><span class="status-dot running"></span><div><small>智能分析中</small><strong>{{ overview.running ?? '—' }}</strong></div></article><article><span class="status-dot review"></span><div><small>待人工审核</small><strong>{{ overview.review ?? '—' }}</strong></div></article><article><span class="status-dot risk"></span><div><small>高风险诊断</small><strong>{{ overview.highRisk ?? '—' }}</strong></div></article><article><span class="status-dot done"></span><div><small>已确认结论</small><strong>{{ overview.confirmed ?? '—' }}</strong></div></article></section>
<el-alert v-if="linkedContext" title="当前列表已限定为业务来源关联诊断；可重置筛选查看全部。" type="info" show-icon :closable="false"/><el-card shadow="never" class="filter-card"><el-form inline @submit.prevent="search"><el-form-item label="触发来源"><el-select v-model="filters.triggerType" clearable :disabled="linkedContext" placeholder="全部来源"><el-option v-for="x in ['INSPECTION_ABNORMAL','ALARM','MANUAL']" :key="x" :label="displayValue(x)" :value="x"/></el-select></el-form-item><el-form-item label="设备"><el-select v-model="filters.deviceId" filterable remote clearable :remote-method="searchDevices" placeholder="按设备名称或编码搜索"><el-option v-for="d in deviceOptions" :key="d.id" :label="deviceLabel(d)" :value="d.id"/></el-select></el-form-item><el-form-item label="诊断状态"><el-select v-model="filters.diagnosisStatus" clearable placeholder="全部状态"><el-option v-for="x in ['PENDING','RUNNING','SUCCEEDED','FAILED']" :key="x" :label="diagnosisLabel(x)" :value="x"/></el-select></el-form-item><el-form-item label="确认状态"><el-select v-model="filters.confirmationStatus" clearable placeholder="全部状态"><el-option v-for="x in ['PENDING','CONFIRMED','REJECTED']" :key="x" :label="confirmationLabel(x)" :value="x"/></el-select></el-form-item><el-form-item label="风险等级"><el-select v-model="filters.riskLevel" clearable placeholder="全部风险"><el-option v-for="x in ['LOW','MEDIUM','HIGH','CRITICAL']" :key="x" :label="displayValue(x)" :value="x"/></el-select></el-form-item><el-form-item><el-button type="primary" @click="search">查询</el-button><el-button @click="reset">重置</el-button></el-form-item></el-form></el-card>
<el-card shadow="never"><el-alert v-if="errorMessage" :title="errorMessage" type="error" show-icon :closable="false"><template #default><el-button link @click="load">重新加载</el-button></template></el-alert><el-table v-else v-loading="loading" :data="rows"><el-table-column prop="diagnosisCode" label="诊断编号" min-width="180"/><el-table-column label="设备" min-width="220"><template #default="s">{{deviceNames[s.row.deviceId]||'设备信息加载中'}}</template></el-table-column><el-table-column label="来源" width="125"><template #default="s">{{displayValue(s.row.triggerType)}}</template></el-table-column><el-table-column label="诊断状态" width="125"><template #default="s"><span class="analysis-status" :class="s.row.diagnosisStatus.toLowerCase()"><i></i>{{diagnosisLabel(s.row.diagnosisStatus)}}</span></template></el-table-column><el-table-column label="人工状态" width="105"><template #default="s"><el-tag size="small" :type="s.row.confirmationStatus==='REJECTED'?'danger':s.row.confirmationStatus==='CONFIRMED'?'success':'info'">{{confirmationLabel(s.row.confirmationStatus)}}</el-tag></template></el-table-column><el-table-column label="风险" width="105"><template #default="s"><el-tag size="small" :type="s.row.riskLevel==='HIGH'||s.row.riskLevel==='CRITICAL'?'danger':s.row.riskLevel==='MEDIUM'?'warning':'success'">{{displayValue(s.row.riskLevel)}}</el-tag></template></el-table-column><el-table-column label="关联工单" min-width="175"><template #default="s"><el-button v-if="workOrders[s.row.id]" link @click="router.push(`/maintenance/work-orders/${workOrders[s.row.id]!.id}`)">{{workOrders[s.row.id]!.workOrderCode}}</el-button><span v-else class="muted">{{auth.can('maintenance:view')?'—':'无查看权限'}}</span></template></el-table-column><el-table-column label="诊断时间" min-width="165"><template #default="s">{{dateTime(s.row.createdAt)}}</template></el-table-column><el-table-column label="操作" width="100" fixed="right"><template #default="s"><el-button link type="primary" @click="router.push(`/ai/diagnoses/${s.row.id}`)">查看报告</el-button></template></el-table-column></el-table><el-empty v-if="!loading&&!errorMessage&&!rows.length" description="暂无符合条件的智能诊断"/><el-pagination v-if="!errorMessage&&total>pageSize" v-model:current-page="page" :total="total" :page-size="pageSize" layout="prev, pager, next, total" @current-change="load"/></el-card>
<el-dialog v-model="createVisible" title="发起智能诊断" width="650px" :close-on-click-modal="false" :before-close="closeCreate"><el-alert :title="diagnosing?(progressMessage||'正在启动智能诊断'):'系统将自动汇聚设备、巡检、维修及标准作业信息，并进行智能风险研判。'" :type="connectionState==='disconnected'&&diagnosing?'warning':'info'" show-icon :closable="false"/><p v-if="diagnosing" class="connection-hint">{{connectionState==='connected'?'实时更新中':connectionState==='connecting'?'正在建立实时连接':'实时更新暂时中断，诊断仍在后台继续'}}</p><el-form label-width="95px" class="dialog-form"><el-form-item label="诊断设备" required><el-select v-model="form.deviceId" filterable remote :remote-method="searchDevices" placeholder="按设备名称或编码搜索"><el-option v-for="d in deviceOptions" :key="d.id" :label="deviceLabel(d)" :value="d.id"/></el-select></el-form-item><el-form-item label="异常摘要" required><el-input v-model="form.abnormalSummary" maxlength="200" show-word-limit/></el-form-item><el-form-item label="补充描述"><el-input v-model="form.userDescription" type="textarea" :rows="4"/></el-form-item></el-form><template #footer><el-button :disabled="diagnosing" @click="closeCreate">取消</el-button><el-button type="primary" :loading="diagnosing" :disabled="diagnosing" @click="create">开始智能诊断</el-button></template></el-dialog></section></template>
<style scoped>.business-page{display:flex;flex-direction:column;gap:16px}.filter-card :deep(.el-select){width:190px}.business-page :deep(.el-pagination){justify-content:flex-end;margin-top:18px}.dialog-form{margin-top:18px}.dialog-form :deep(.el-select){width:100%}.connection-hint{color:var(--el-text-color-secondary);font-size:13px}.analysis-status{display:inline-flex;align-items:center;gap:7px}.analysis-status i{width:7px;height:7px;border-radius:50%;background:#94a3ad}.analysis-status.running i{background:#24a9bb;box-shadow:0 0 0 5px rgba(36,169,187,.12);animation:status-pulse 1.7s infinite}.analysis-status.succeeded i{background:#36a373}.analysis-status.failed i{background:#d25c5c}.muted{color:#9aa6ad}.ai-overview{display:grid;grid-template-columns:minmax(240px,1.35fr) repeat(4,minmax(125px,.7fr));overflow:hidden;border:1px solid #263d4d;border-radius:14px;background:linear-gradient(125deg,#101a23,#172b38);box-shadow:0 12px 28px rgba(13,36,50,.13);color:#eaf6f8}.overview-title,.ai-overview article{display:flex;align-items:center;gap:12px;min-height:82px;padding:16px 20px}.overview-title{border-right:1px solid rgba(139,185,200,.15)}.overview-title div,.ai-overview article div{display:flex;flex-direction:column;gap:5px}.overview-title small,.ai-overview article small{color:#829ba8;font-size:11px}.overview-orb{display:grid;width:38px;height:38px;place-items:center;border:1px solid #4bb8c6;border-radius:50%;background:rgba(64,190,205,.1);color:#71d8e4;font-size:12px;font-weight:800}.ai-overview article{border-left:1px solid rgba(139,185,200,.1)}.ai-overview article strong{font-size:23px}.status-dot{width:8px;height:8px;border-radius:50%;background:#6d7d86}.status-dot.running{background:#42cad9;box-shadow:0 0 0 5px rgba(66,202,217,.1);animation:status-pulse 1.8s infinite}.status-dot.review{background:#ddb663}.status-dot.risk{background:#e47766}.status-dot.done{background:#61b58e}@keyframes status-pulse{50%{opacity:.45;transform:scale(.82)}}@media(max-width:1100px){.ai-overview{grid-template-columns:repeat(4,1fr)}.overview-title{grid-column:1/-1;border-right:0;border-bottom:1px solid rgba(139,185,200,.15)}.ai-overview article:first-of-type{border-left:0}}@media(max-width:760px){.ai-overview{grid-template-columns:1fr 1fr}.overview-title{grid-column:1/-1}.ai-overview article:nth-of-type(odd){border-left:0}}</style>
