<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { ElMessage, ElMessageBox } from 'element-plus';
import { request } from '../api/request';
import { useAuthStore } from '../stores/auth';
import type { Device, PageResult } from '../types/device';
import type { Diagnosis, DiagnosisView } from '../types/maintenance';
import { displayValue } from '../utils/display';
const route=useRoute(),router=useRouter(),auth=useAuthStore(),rows=ref<Diagnosis[]>([]),total=ref(0),page=ref(1),loading=ref(false),errorMessage=ref(''),deviceOptions=ref<Device[]>([]),deviceNames=reactive<Record<string,string>>({}),createVisible=ref(false),diagnosing=ref(false);
const pageSize=20,filters=reactive({triggerType:String(route.query.triggerType||''),triggerId:String(route.query.triggerId||''),deviceId:String(route.query.deviceId||''),diagnosisStatus:'',riskLevel:'',confirmationStatus:''}),form=reactive({deviceId:'',abnormalSummary:'',userDescription:''}),snapshot=ref('');
const linkedContext=computed(()=>Boolean(filters.triggerId)),canManual=computed(()=>auth.can('ai:diagnosis')&&!auth.roles.includes('INSPECTOR'));
const dateTime=(v:string)=>v?v.replace('T',' ').slice(0,19):'-',deviceLabel=(d:Device)=>`${d.deviceName}（${d.deviceCode}）`;
async function searchDevices(keyword=''){const p=await request.get<never,PageResult<Device>>('/api/device/devices',{params:{pageNum:1,pageSize:20,keyword:keyword||undefined}});deviceOptions.value=p.records??[];deviceOptions.value.forEach(d=>deviceNames[d.id]=deviceLabel(d));}
async function resolveDevices(data:Diagnosis[]){await Promise.allSettled([...new Set(data.map(x=>x.deviceId))].filter(id=>!deviceNames[id]).map(async id=>{const d=await request.get<never,Device>(`/api/device/devices/${id}`,{silentStatuses:[404]});deviceNames[id]=deviceLabel(d);}));}
async function load(){loading.value=true;errorMessage.value='';try{const p=await request.get<never,PageResult<Diagnosis>>('/api/ai/diagnoses',{params:{pageNum:page.value,pageSize,...Object.fromEntries(Object.entries(filters).map(([k,v])=>[k,v||undefined]))}});rows.value=p.records??[];total.value=p.total??0;await resolveDevices(rows.value);}catch{errorMessage.value='AI 诊断列表加载失败，请稍后重试。';}finally{loading.value=false;}}
function search(){page.value=1;void load()}function reset(){Object.assign(filters,{triggerType:'',triggerId:'',deviceId:'',diagnosisStatus:'',riskLevel:'',confirmationStatus:''});void router.replace({path:route.path});search()}
function openCreate(){Object.assign(form,{deviceId:'',abnormalSummary:'',userDescription:''});snapshot.value=JSON.stringify(form);createVisible.value=true;void searchDevices()}
async function closeCreate(){if(JSON.stringify(form)!==snapshot.value){try{await ElMessageBox.confirm('诊断描述尚未提交，确定放弃吗？','放弃诊断',{type:'warning'});}catch{return}}createVisible.value=false}
async function create(){if(!form.deviceId)return void ElMessage.warning('请选择诊断设备');if(!form.abnormalSummary.trim())return void ElMessage.warning('请填写异常摘要');diagnosing.value=true;try{const v=await request.post<never,DiagnosisView>('/api/ai/diagnoses',{triggerType:'MANUAL',triggerId:null,...form});createVisible.value=false;ElMessage.success('同步诊断已完成，请进行人工确认');await router.push(`/ai/diagnoses/${v.diagnosis.id}`);}finally{diagnosing.value=false;}}
onMounted(()=>{void searchDevices();void load()});
</script>
<template><section class="business-page"><div class="page-head"><div><h1>AI 诊断</h1><p>DeepSeek 通过固定五节点同步生成结构化辅助诊断，最终决定仍由业务人员确认。</p></div><el-button v-if="canManual" type="primary" @click="openCreate">人工发起诊断</el-button></div><el-alert v-if="linkedContext" title="当前列表已限定为业务来源关联诊断；可重置筛选查看全部。" type="info" show-icon :closable="false"/><el-card shadow="never" class="filter-card"><el-form inline @submit.prevent="search"><el-form-item label="触发来源"><el-select v-model="filters.triggerType" clearable :disabled="linkedContext" placeholder="全部来源"><el-option v-for="x in ['INSPECTION_ABNORMAL','ALARM','MANUAL']" :key="x" :label="displayValue(x)" :value="x"/></el-select></el-form-item><el-form-item label="设备"><el-select v-model="filters.deviceId" filterable remote clearable :remote-method="searchDevices" placeholder="按设备名称或编码搜索"><el-option v-for="d in deviceOptions" :key="d.id" :label="deviceLabel(d)" :value="d.id"/></el-select></el-form-item><el-form-item label="诊断状态"><el-select v-model="filters.diagnosisStatus" clearable placeholder="全部状态"><el-option v-for="x in ['PENDING','RUNNING','SUCCEEDED','FAILED']" :key="x" :label="displayValue(x)" :value="x"/></el-select></el-form-item><el-form-item label="确认状态"><el-select v-model="filters.confirmationStatus" clearable placeholder="全部状态"><el-option v-for="x in ['PENDING','CONFIRMED','REJECTED']" :key="x" :label="displayValue(x)" :value="x"/></el-select></el-form-item><el-form-item label="风险等级"><el-select v-model="filters.riskLevel" clearable placeholder="全部风险"><el-option v-for="x in ['LOW','MEDIUM','HIGH','CRITICAL']" :key="x" :label="displayValue(x)" :value="x"/></el-select></el-form-item><el-form-item><el-button type="primary" @click="search">查询</el-button><el-button @click="reset">重置</el-button></el-form-item></el-form></el-card>
<el-card shadow="never"><el-alert v-if="errorMessage" :title="errorMessage" type="error" show-icon :closable="false"><template #default><el-button link @click="load">重新加载</el-button></template></el-alert><el-table v-else v-loading="loading" :data="rows"><el-table-column prop="diagnosisCode" label="诊断编号" min-width="180"/><el-table-column label="设备" min-width="220"><template #default="s">{{deviceNames[s.row.deviceId]||'设备信息加载中'}}</template></el-table-column><el-table-column label="来源" width="125"><template #default="s">{{displayValue(s.row.triggerType)}}</template></el-table-column><el-table-column label="诊断状态" width="105"><template #default="s"><el-tag :type="s.row.diagnosisStatus==='FAILED'?'danger':s.row.diagnosisStatus==='SUCCEEDED'?'success':'info'">{{displayValue(s.row.diagnosisStatus)}}</el-tag></template></el-table-column><el-table-column label="人工确认" width="105"><template #default="s">{{displayValue(s.row.confirmationStatus)}}</template></el-table-column><el-table-column label="风险" width="95"><template #default="s">{{displayValue(s.row.riskLevel)}}</template></el-table-column><el-table-column label="创建时间" min-width="165"><template #default="s">{{dateTime(s.row.createdAt)}}</template></el-table-column><el-table-column label="操作" width="100" fixed="right"><template #default="s"><el-button link type="primary" @click="router.push(`/ai/diagnoses/${s.row.id}`)">查看诊断</el-button></template></el-table-column></el-table><el-empty v-if="!loading&&!errorMessage&&!rows.length" description="暂无符合条件的 AI 诊断"/><el-pagination v-if="!errorMessage&&total>pageSize" v-model:current-page="page" :total="total" :page-size="pageSize" layout="prev, pager, next, total" @current-change="load"/></el-card>
<el-dialog v-model="createVisible" title="人工发起 AI 诊断" width="650px" :close-on-click-modal="false" :before-close="closeCreate"><el-alert title="该操作会同步调用 DeepSeek 并依次执行固定五节点，通常需要数十秒。" type="info" show-icon :closable="false"/><el-form label-width="95px" class="dialog-form"><el-form-item label="诊断设备" required><el-select v-model="form.deviceId" filterable remote :remote-method="searchDevices" placeholder="按设备名称或编码搜索"><el-option v-for="d in deviceOptions" :key="d.id" :label="deviceLabel(d)" :value="d.id"/></el-select></el-form-item><el-form-item label="异常摘要" required><el-input v-model="form.abnormalSummary" maxlength="200" show-word-limit/></el-form-item><el-form-item label="补充描述"><el-input v-model="form.userDescription" type="textarea" :rows="4"/></el-form-item></el-form><template #footer><el-button :disabled="diagnosing" @click="closeCreate">取消</el-button><el-button type="primary" :loading="diagnosing" @click="create">开始同步诊断</el-button></template></el-dialog></section></template>
<style scoped>.business-page{display:flex;flex-direction:column;gap:16px}.filter-card :deep(.el-select){width:190px}.business-page :deep(.el-pagination){justify-content:flex-end;margin-top:18px}.dialog-form{margin-top:18px}.dialog-form :deep(.el-select){width:100%}</style>
