<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { ElMessage, ElMessageBox } from 'element-plus';
import { request } from '../api/request';
import { useAuthStore } from '../stores/auth';
import type { Device, PageResult } from '../types/device';
import type { Diagnosis, DiagnosisView, WorkOrder } from '../types/maintenance';
import { displayValue } from '../utils/display';
import { notificationSocket, type ConnectionState, type NotificationMessage } from '../services/notificationSocket';
const route=useRoute(),router=useRouter(),auth=useAuthStore(),rows=ref<Diagnosis[]>([]),total=ref(0),page=ref(1),loading=ref(false),errorMessage=ref(''),deviceOptions=ref<Device[]>([]),deviceNames=reactive<Record<string,string>>({}),workOrders=reactive<Record<string,WorkOrder|null>>({}),createVisible=ref(false),diagnosing=ref(false),connectionState=ref<ConnectionState>('disconnected'),progressMessage=ref('');
let unsubscribeMessage:undefined|(()=>void),unsubscribeState:undefined|(()=>void);
const pageSize=20,filters=reactive({triggerType:String(route.query.triggerType||''),triggerId:String(route.query.triggerId||''),deviceId:String(route.query.deviceId||''),diagnosisStatus:'',riskLevel:'',confirmationStatus:''}),form=reactive({deviceId:'',abnormalSummary:'',userDescription:''}),snapshot=ref('');
const linkedContext=computed(()=>Boolean(filters.triggerId)),canManual=computed(()=>auth.can('ai:diagnosis')&&!auth.roles.includes('INSPECTOR'));
const dateTime=(v:string)=>v?v.replace('T',' ').slice(0,19):'-',deviceLabel=(d:Device)=>`${d.deviceName}（${d.deviceCode}）`;
async function searchDevices(keyword=''){const p=await request.get<never,PageResult<Device>>('/api/device/devices',{params:{pageNum:1,pageSize:20,keyword:keyword||undefined}});deviceOptions.value=p.records??[];deviceOptions.value.forEach(d=>deviceNames[d.id]=deviceLabel(d));}
async function resolveDevices(data:Diagnosis[]){await Promise.allSettled([...new Set(data.map(x=>x.deviceId))].filter(id=>!deviceNames[id]).map(async id=>{const d=await request.get<never,Device>(`/api/device/devices/${id}`,{silentStatuses:[404]});deviceNames[id]=deviceLabel(d);}));}
async function resolveWorkOrders(data:Diagnosis[]){if(!auth.can('maintenance:view'))return;await Promise.allSettled(data.filter(x=>workOrders[x.id]===undefined).map(async diagnosis=>{const p=await request.get<never,PageResult<WorkOrder>>('/api/maintenance/work-orders',{params:{aiDiagnosisId:diagnosis.id,pageNum:1,pageSize:1}});workOrders[diagnosis.id]=p.records?.[0]??null;}));}
async function load(){loading.value=true;errorMessage.value='';try{const p=await request.get<never,PageResult<Diagnosis>>('/api/ai/diagnoses',{params:{pageNum:page.value,pageSize,...Object.fromEntries(Object.entries(filters).map(([k,v])=>[k,v||undefined]))}});rows.value=p.records??[];total.value=p.total??0;await Promise.all([resolveDevices(rows.value),resolveWorkOrders(rows.value)]);}catch{errorMessage.value='AI 诊断列表加载失败，请稍后重试。';}finally{loading.value=false;}}
function search(){page.value=1;void load()}function reset(){Object.assign(filters,{triggerType:'',triggerId:'',deviceId:'',diagnosisStatus:'',riskLevel:'',confirmationStatus:''});void router.replace({path:route.path});search()}
function openCreate(){Object.assign(form,{deviceId:'',abnormalSummary:'',userDescription:''});snapshot.value=JSON.stringify(form);createVisible.value=true;void searchDevices()}
async function closeCreate(){if(JSON.stringify(form)!==snapshot.value){try{await ElMessageBox.confirm('诊断描述尚未提交，确定放弃吗？','放弃诊断',{type:'warning'});}catch{return}}createVisible.value=false}
function onWorkflowEvent(message:NotificationMessage){if(!diagnosing.value||message.notificationType!=='AI_WORKFLOW'||message.bizType!=='AI_DIAGNOSIS'||!message.bizId)return;try{const event=JSON.parse(message.content) as {nodeCode?:string;nodeStatus?:string;message?:string};progressMessage.value=[event.nodeCode?displayValue(event.nodeCode):'',event.message||''].filter(Boolean).join(' · ');}catch{progressMessage.value='诊断状态已更新';}void router.push(`/ai/diagnoses/${message.bizId}`);}
async function create(){if(!form.deviceId)return void ElMessage.warning('请选择诊断设备');if(!form.abnormalSummary.trim())return void ElMessage.warning('请填写异常摘要');diagnosing.value=true;progressMessage.value='正在创建诊断任务';try{const v=await request.post<never,DiagnosisView>('/api/ai/diagnoses',{triggerType:'MANUAL',triggerId:null,...form});createVisible.value=false;ElMessage.success(v.diagnosis.diagnosisStatus==='SUCCEEDED'?'诊断已完成，请进行人工确认':'诊断执行结束，请查看详情');await router.push(`/ai/diagnoses/${v.diagnosis.id}`);}catch(e:any){if(!e.response)ElMessage.warning('连接已中断，诊断可能仍在执行，请刷新诊断列表确认真实状态。');}finally{diagnosing.value=false;}}
onMounted(()=>{unsubscribeMessage=notificationSocket.subscribe(onWorkflowEvent);unsubscribeState=notificationSocket.subscribeState(state=>connectionState.value=state);void searchDevices();void load()});
onBeforeUnmount(()=>{unsubscribeMessage?.();unsubscribeState?.();});
</script>
<template><section class="business-page"><div class="page-head"><div><h1>AI 诊断</h1><p>DeepSeek 通过固定五节点同步生成结构化辅助诊断，最终决定仍由业务人员确认。</p></div><el-button v-if="canManual" type="primary" @click="openCreate">人工发起诊断</el-button></div><el-alert v-if="linkedContext" title="当前列表已限定为业务来源关联诊断；可重置筛选查看全部。" type="info" show-icon :closable="false"/><el-card shadow="never" class="filter-card"><el-form inline @submit.prevent="search"><el-form-item label="触发来源"><el-select v-model="filters.triggerType" clearable :disabled="linkedContext" placeholder="全部来源"><el-option v-for="x in ['INSPECTION_ABNORMAL','ALARM','MANUAL']" :key="x" :label="displayValue(x)" :value="x"/></el-select></el-form-item><el-form-item label="设备"><el-select v-model="filters.deviceId" filterable remote clearable :remote-method="searchDevices" placeholder="按设备名称或编码搜索"><el-option v-for="d in deviceOptions" :key="d.id" :label="deviceLabel(d)" :value="d.id"/></el-select></el-form-item><el-form-item label="诊断状态"><el-select v-model="filters.diagnosisStatus" clearable placeholder="全部状态"><el-option v-for="x in ['PENDING','RUNNING','SUCCEEDED','FAILED']" :key="x" :label="displayValue(x)" :value="x"/></el-select></el-form-item><el-form-item label="确认状态"><el-select v-model="filters.confirmationStatus" clearable placeholder="全部状态"><el-option v-for="x in ['PENDING','CONFIRMED','REJECTED']" :key="x" :label="displayValue(x)" :value="x"/></el-select></el-form-item><el-form-item label="风险等级"><el-select v-model="filters.riskLevel" clearable placeholder="全部风险"><el-option v-for="x in ['LOW','MEDIUM','HIGH','CRITICAL']" :key="x" :label="displayValue(x)" :value="x"/></el-select></el-form-item><el-form-item><el-button type="primary" @click="search">查询</el-button><el-button @click="reset">重置</el-button></el-form-item></el-form></el-card>
<el-card shadow="never"><el-alert v-if="errorMessage" :title="errorMessage" type="error" show-icon :closable="false"><template #default><el-button link @click="load">重新加载</el-button></template></el-alert><el-table v-else v-loading="loading" :data="rows"><el-table-column prop="diagnosisCode" label="诊断编号" min-width="180"/><el-table-column label="设备" min-width="220"><template #default="s">{{deviceNames[s.row.deviceId]||'设备信息加载中'}}</template></el-table-column><el-table-column label="来源" width="125"><template #default="s">{{displayValue(s.row.triggerType)}}</template></el-table-column><el-table-column label="诊断状态" width="105"><template #default="s"><el-tag :type="s.row.diagnosisStatus==='FAILED'?'danger':s.row.diagnosisStatus==='SUCCEEDED'?'success':'info'">{{displayValue(s.row.diagnosisStatus)}}</el-tag></template></el-table-column><el-table-column label="人工确认" width="105"><template #default="s">{{displayValue(s.row.confirmationStatus)}}</template></el-table-column><el-table-column label="风险" width="95"><template #default="s">{{displayValue(s.row.riskLevel)}}</template></el-table-column><el-table-column label="关联工单" min-width="175"><template #default="s"><el-button v-if="workOrders[s.row.id]" link @click="router.push(`/maintenance/work-orders/${workOrders[s.row.id]!.id}`)">{{workOrders[s.row.id]!.workOrderCode}}</el-button><span v-else>{{auth.can('maintenance:view')?'未创建':'无查看权限'}}</span></template></el-table-column><el-table-column label="诊断时间" min-width="165"><template #default="s">{{dateTime(s.row.createdAt)}}</template></el-table-column><el-table-column label="操作" width="100" fixed="right"><template #default="s"><el-button link type="primary" @click="router.push(`/ai/diagnoses/${s.row.id}`)">查看诊断</el-button></template></el-table-column></el-table><el-empty v-if="!loading&&!errorMessage&&!rows.length" description="暂无符合条件的 AI 诊断"/><el-pagination v-if="!errorMessage&&total>pageSize" v-model:current-page="page" :total="total" :page-size="pageSize" layout="prev, pager, next, total" @current-change="load"/></el-card>
<el-dialog v-model="createVisible" title="人工发起 AI 诊断" width="650px" :close-on-click-modal="false" :before-close="closeCreate"><el-alert :title="diagnosing?(progressMessage||'AI 诊断生成中'):'该操作会同步调用 DeepSeek 并依次执行固定五节点，通常需要数十秒。'" :type="connectionState==='disconnected'&&diagnosing?'warning':'info'" show-icon :closable="false"/><p v-if="diagnosing" class="connection-hint">实时连接：{{connectionState==='connected'?'已连接':connectionState==='connecting'?'连接中':'已断开，后端任务不会因此失败'}}</p><el-form label-width="95px" class="dialog-form"><el-form-item label="诊断设备" required><el-select v-model="form.deviceId" filterable remote :remote-method="searchDevices" placeholder="按设备名称或编码搜索"><el-option v-for="d in deviceOptions" :key="d.id" :label="deviceLabel(d)" :value="d.id"/></el-select></el-form-item><el-form-item label="异常摘要" required><el-input v-model="form.abnormalSummary" maxlength="200" show-word-limit/></el-form-item><el-form-item label="补充描述"><el-input v-model="form.userDescription" type="textarea" :rows="4"/></el-form-item></el-form><template #footer><el-button :disabled="diagnosing" @click="closeCreate">取消</el-button><el-button type="primary" :loading="diagnosing" :disabled="diagnosing" @click="create">开始同步诊断</el-button></template></el-dialog></section></template>
<style scoped>.business-page{display:flex;flex-direction:column;gap:16px}.filter-card :deep(.el-select){width:190px}.business-page :deep(.el-pagination){justify-content:flex-end;margin-top:18px}.dialog-form{margin-top:18px}.dialog-form :deep(.el-select){width:100%}.connection-hint{color:var(--el-text-color-secondary);font-size:13px}</style>
