<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue';
import { onBeforeRouteLeave, useRoute, useRouter } from 'vue-router';
import { ElMessage, ElMessageBox } from 'element-plus';
import { request } from '../api/request';
import { useAuthStore } from '../stores/auth';
import type { Device, PageResult, UserSummary } from '../types/device';
import type { Defect, DiagnosisView, WorkOrderDetailData } from '../types/maintenance';
import { displayValue } from '../utils/display';
const route=useRoute(),router=useRouter(),auth=useAuthStore(),detail=ref<WorkOrderDetailData>(),device=ref<Device>(),defect=ref<Defect>(),diagnosis=ref<DiagnosisView>(),loading=ref(false),errorMessage=ref(''),busy=ref('');
const userNames=reactive<Record<string,string>>({}),maintainers=ref<UserSummary[]>([]),assignVisible=ref(false),repairVisible=ref(false),acceptVisible=ref(false);
const assignForm=reactive({assigneeUserId:'',comment:''}),repairForm=reactive({faultCause:'',solution:'',partsUsed:'',downtimeMinutes:null as number|null,maintenanceCost:null as number|null,result:'SUCCESS',comment:''}),acceptForm=reactive({acceptanceResult:'PASSED',acceptanceContent:'',comment:''}),snapshots=reactive({assign:'',repair:'',accept:''});
const order=computed(()=>detail.value?.workOrder),isAdmin=computed(()=>auth.roles.includes('ADMIN')||auth.roles.includes('SUPER_ADMIN')),isAssignee=computed(()=>order.value?.assigneeUserId===auth.currentUser?.id),canRepair=computed(()=>auth.roles.includes('MAINTAINER')&&auth.can('maintenance:workorder:process')&&isAssignee.value),dirty=computed(()=>assignVisible.value&&JSON.stringify(assignForm)!==snapshots.assign||repairVisible.value&&JSON.stringify(repairForm)!==snapshots.repair||acceptVisible.value&&JSON.stringify(acceptForm)!==snapshots.accept);
const dateTime=(v:string|null|undefined)=>v?v.replace('T',' ').slice(0,19):'-',userLabel=(u:UserSummary)=>u.realName?`${u.realName}（${u.username}）`:u.username;
function person(id:string|null|undefined){if(!id)return '未分派';if(id===auth.currentUser?.id)return `${auth.currentUser.realName||auth.currentUser.username}（本人）`;return userNames[id]||(auth.can('system:user:view')?'人员信息加载中':'业务人员')}
async function resolveUsers(ids:(string|null|undefined)[]){if(!auth.can('system:user:view'))return;await Promise.allSettled([...new Set(ids.filter(Boolean) as string[])].filter(id=>!userNames[id]).map(async id=>{try{const u=await request.get<never,UserSummary>(`/api/auth/users/${id}`,{silentStatuses:[404]});userNames[id]=userLabel(u);}catch(e:any){userNames[id]=e.response?.status===404?'原操作人（账号已删除）':'人员信息暂不可用';}}));}
async function load(){loading.value=true;errorMessage.value='';try{const d=await request.get<never,WorkOrderDetailData>(`/api/maintenance/work-orders/${route.params.id}`);detail.value=d;const o=d.workOrder;const jobs:Promise<unknown>[]=[request.get<never,Device>(`/api/device/devices/${o.deviceId}`).then(x=>device.value=x)];if(o.defectId)jobs.push(request.get<never,Defect>(`/api/maintenance/defects/${o.defectId}`).then(x=>defect.value=x));else defect.value=undefined;if(o.aiDiagnosisId)jobs.push(request.get<never,DiagnosisView>(`/api/ai/diagnoses/${o.aiDiagnosisId}`).then(x=>diagnosis.value=x));else diagnosis.value=undefined;jobs.push(resolveUsers([o.creatorUserId,o.assigneeUserId,...d.logs.map(x=>x.operatorUserId),...d.records.map(x=>x.repairedBy),...d.acceptances.map(x=>x.acceptedBy)]));await Promise.allSettled(jobs);}catch{errorMessage.value='工单详情加载失败，可能超出当前维修人员的数据范围。';}finally{loading.value=false;}}
async function searchMaintainers(keyword=''){if(!auth.can('system:user:view'))return;const p=await request.get<never,PageResult<UserSummary>>('/api/auth/users',{params:{pageNum:1,pageSize:20,keyword:keyword||undefined,status:'ENABLED',roleCode:'MAINTAINER'}});maintainers.value=p.records??[];maintainers.value.forEach(u=>userNames[u.id]=userLabel(u));}
function openAssign(){Object.assign(assignForm,{assigneeUserId:'',comment:''});snapshots.assign=JSON.stringify(assignForm);assignVisible.value=true;void searchMaintainers()}function openRepair(){Object.assign(repairForm,{faultCause:'',solution:'',partsUsed:'',downtimeMinutes:null,maintenanceCost:null,result:'SUCCESS',comment:''});snapshots.repair=JSON.stringify(repairForm);repairVisible.value=true}function openAccept(){Object.assign(acceptForm,{acceptanceResult:'PASSED',acceptanceContent:'',comment:''});snapshots.accept=JSON.stringify(acceptForm);acceptVisible.value=true}
async function closeDialog(kind:'assign'|'repair'|'accept'){const visible={assign:assignVisible,repair:repairVisible,accept:acceptVisible}[kind],form={assign:assignForm,repair:repairForm,accept:acceptForm}[kind];if(JSON.stringify(form)!==snapshots[kind]){try{await ElMessageBox.confirm('表单尚未提交，确定放弃吗？','放弃编辑',{type:'warning'});}catch{return}}visible.value=false}
const successMessages: Record<string, string> = { assign: '工单已分派给维修人员。', start: '维修已开始，工单进入处理中状态。', 'repair-result': '维修记录已提交，工单进入待验收状态。' };
async function execute(kind:'assign'|'start'|'repair-result'|'acceptance',body?:unknown,params?:unknown){if(!order.value||busy.value)return;busy.value=kind;try{await request.post(`/api/maintenance/work-orders/${order.value.id}/${kind}`,body,{params});if(kind==='acceptance'){const result=(body as any)?.acceptanceResult;ElMessage.success(result==='PASSED'?'验收通过，维修工单已完成。':'验收已驳回，工单返回维修处理中。');}else{ElMessage.success(successMessages[kind]||'工单操作成功');}assignVisible.value=repairVisible.value=acceptVisible.value=false;await load();}catch(e:any){if(e.response?.status===409)await load();}finally{busy.value='';}}
async function submitAssign(){if(busy.value)return;if(!assignForm.assigneeUserId)return void ElMessage.warning('请选择启用的维修人员');try{await ElMessageBox.confirm('确认将工单分派给所选维修人员吗？','确认分派',{type:'warning'});await execute('assign',{...assignForm})}catch{/* 取消 */}}async function start(){if(busy.value)return;try{const {value}=await ElMessageBox.prompt('可填写开工说明','开始维修',{inputPlaceholder:'选填'});await execute('start',undefined,{comment:value||undefined});}catch{/* 取消 */}}async function submitRepair(){if(busy.value)return;if(!repairForm.solution.trim())return void ElMessage.warning('请填写维修方案');try{await ElMessageBox.confirm('确认提交维修结果并进入待验收吗？','提交维修结果',{type:'warning'});await execute('repair-result',{...repairForm})}catch{/* 取消 */}}async function submitAccept(){if(busy.value)return;if(!acceptForm.acceptanceContent.trim())return void ElMessage.warning('请填写验收说明');if(acceptForm.acceptanceResult==='REJECTED'&&!acceptForm.comment.trim())return void ElMessage.warning('驳回时必须填写原因');try{await ElMessageBox.confirm(acceptForm.acceptanceResult==='PASSED'?'验收通过将完成工单并解决关联缺陷，确认提交吗？':'确认驳回并退回维修中吗？','提交验收',{type:'warning'});await execute('acceptance',{...acceptForm})}catch{/* 取消 */}}
function beforeUnload(event:BeforeUnloadEvent){if(!dirty.value)return;event.preventDefault();event.returnValue='';}
onBeforeRouteLeave(async()=>{if(!dirty.value)return true;try{await ElMessageBox.confirm('当前表单尚未提交，确定离开吗？','离开页面',{type:'warning'});return true}catch{return false}});onMounted(()=>{window.addEventListener('beforeunload',beforeUnload);void load();});onBeforeUnmount(()=>window.removeEventListener('beforeunload',beforeUnload));
</script>
<template><section class="detail-page"><div class="page-head"><div><el-button link @click="router.push('/maintenance/work-orders')">← 返回工单列表</el-button><h1>维修工单详情</h1><p>按分派、开始维修、提交结果和管理员验收的职责链推进工单。</p></div><div v-if="order" class="head-actions"><el-button v-if="isAdmin&&auth.can('maintenance:workorder:process')&&order.status==='PENDING'" type="primary" @click="openAssign">分派工单</el-button><el-button v-if="canRepair&&order.status==='ASSIGNED'" type="primary" :loading="busy==='start'" @click="start">开始维修</el-button><el-button v-if="canRepair&&order.status==='PROCESSING'" type="primary" @click="openRepair">提交维修结果</el-button><el-button v-if="isAdmin&&auth.can('maintenance:workorder:accept')&&!isAssignee&&order.status==='WAITING_ACCEPTANCE'" type="success" @click="openAccept">验收工单</el-button></div></div>
<el-card v-if="order" shadow="never"><el-steps :active="['PENDING','ASSIGNED','PROCESSING','WAITING_ACCEPTANCE','COMPLETED'].indexOf(order.status)" finish-status="success" align-center><el-step v-for="x in ['PENDING','ASSIGNED','PROCESSING','WAITING_ACCEPTANCE','COMPLETED']" :key="x" :title="displayValue(x)"/></el-steps></el-card><el-alert v-if="order?.status==='WAITING_ACCEPTANCE'&&!isAdmin" title="维修结果已提交，正在等待业务管理员验收。" type="info" show-icon :closable="false"/>
<el-alert v-if="errorMessage" :title="errorMessage" type="error" show-icon :closable="false"><template #default><el-button link @click="load">重新加载</el-button></template></el-alert><template v-else-if="order"><el-card v-loading="loading" shadow="never"><template #header><strong>工单信息</strong></template><el-descriptions :column="3" border><el-descriptions-item label="工单编号">{{order.workOrderCode}}</el-descriptions-item><el-descriptions-item label="状态"><el-tag>{{displayValue(order.status)}}</el-tag></el-descriptions-item><el-descriptions-item label="优先级"><el-tag :type="order.priority==='URGENT'||order.priority==='HIGH'?'danger':'info'">{{displayValue(order.priority)}}</el-tag></el-descriptions-item><el-descriptions-item label="标题" :span="2">{{order.title}}</el-descriptions-item><el-descriptions-item label="工单类型">{{displayValue(order.workOrderType)}}</el-descriptions-item><el-descriptions-item label="描述" :span="3">{{order.description||'-'}}</el-descriptions-item><el-descriptions-item label="创建人">{{person(order.creatorUserId)}}</el-descriptions-item><el-descriptions-item label="维修人员">{{person(order.assigneeUserId)}}</el-descriptions-item><el-descriptions-item label="创建时间">{{dateTime(order.createdAt)}}</el-descriptions-item><el-descriptions-item label="计划时段" :span="2">{{dateTime(order.plannedStartTime)}} 至 {{dateTime(order.plannedEndTime)}}</el-descriptions-item><el-descriptions-item label="实际时段">{{dateTime(order.actualStartTime)}} 至 {{dateTime(order.actualEndTime)}}</el-descriptions-item><el-descriptions-item v-if="order.closeResult" label="关闭结论" :span="3">{{order.closeResult}}</el-descriptions-item></el-descriptions></el-card>
<el-row :gutter="16"><el-col :xs="24" :lg="8"><el-card class="full-card" shadow="never"><template #header><strong>设备</strong></template><p>{{device?`${device.deviceName}（${device.deviceCode}）`:'设备信息加载中'}}</p><el-button link @click="router.push(`/devices/${order.deviceId}`)">查看设备详情</el-button></el-card></el-col><el-col :xs="24" :lg="8"><el-card class="full-card" shadow="never"><template #header><strong>关联缺陷</strong></template><template v-if="defect"><p>{{defect.defectCode}} · {{defect.title}}</p><el-tag>{{displayValue(defect.status)}}</el-tag><el-button link @click="router.push(`/maintenance/defects/${defect.id}`)">查看缺陷</el-button></template><el-empty v-else description="无关联缺陷"/></el-card></el-col><el-col :xs="24" :lg="8"><el-card class="full-card" shadow="never"><template #header><strong>AI 诊断</strong></template><template v-if="diagnosis"><p>{{diagnosis.diagnosis.diagnosisCode}}</p><el-tag>{{displayValue(diagnosis.diagnosis.confirmationStatus)}}</el-tag><el-button link @click="router.push(`/ai/diagnoses/${diagnosis.diagnosis.id}`)">查看诊断</el-button></template><el-empty v-else description="未采用 AI 诊断"/></el-card></el-col></el-row>
<el-card shadow="never"><template #header><strong>状态流转日志</strong></template><el-timeline v-if="detail?.logs.length"><el-timeline-item v-for="x in detail.logs" :key="x.id" :timestamp="dateTime(x.createdAt)" placement="top"><strong>{{displayValue(x.action)}}：{{displayValue(x.fromStatus)}} → {{displayValue(x.toStatus)}}</strong><div class="muted">操作人：{{person(x.operatorUserId)}}<span v-if="x.comment"> · {{x.comment}}</span></div></el-timeline-item></el-timeline><el-empty v-else description="暂无流转日志"/></el-card>
<el-card shadow="never"><template #header><strong>维修记录</strong></template><el-table v-if="detail?.records.length" :data="detail.records"><el-table-column prop="faultCause" label="故障原因" min-width="170"/><el-table-column prop="solution" label="维修方案" min-width="210"/><el-table-column prop="partsUsed" label="使用备件" min-width="140"/><el-table-column label="结果" width="105"><template #default="s">{{displayValue(s.row.result)}}</template></el-table-column><el-table-column label="停机/费用" min-width="150"><template #default="s">{{s.row.downtimeMinutes??0}} 分钟 / ¥{{s.row.maintenanceCost??0}}</template></el-table-column><el-table-column label="维修人员" min-width="150"><template #default="s">{{person(s.row.repairedBy)}}</template></el-table-column><el-table-column label="维修时间" min-width="165"><template #default="s">{{dateTime(s.row.repairedAt)}}</template></el-table-column></el-table><el-empty v-else description="尚无维修结果"/></el-card>
<el-card shadow="never"><template #header><strong>验收记录</strong></template><el-table v-if="detail?.acceptances.length" :data="detail.acceptances"><el-table-column label="验收结果" width="120"><template #default="s"><el-tag :type="s.row.acceptanceResult==='PASSED'?'success':'danger'">{{displayValue(s.row.acceptanceResult)}}</el-tag></template></el-table-column><el-table-column prop="acceptanceContent" label="验收说明" min-width="260"/><el-table-column label="验收人" min-width="160"><template #default="s">{{person(s.row.acceptedBy)}}</template></el-table-column><el-table-column label="验收时间" min-width="165"><template #default="s">{{dateTime(s.row.acceptedAt)}}</template></el-table-column></el-table><el-empty v-else description="尚未验收"/></el-card></template>
<el-dialog v-model="assignVisible" title="分派维修工单" width="560px" :close-on-click-modal="!busy" :before-close="()=>closeDialog('assign')"><el-form label-width="90px"><el-form-item label="维修人员" required><el-select v-model="assignForm.assigneeUserId" filterable remote :remote-method="searchMaintainers" :disabled="Boolean(busy)" placeholder="仅可选择启用的维修人员"><el-option v-for="u in maintainers" :key="u.id" :label="userLabel(u)" :value="u.id"/></el-select></el-form-item><el-form-item label="分派说明"><el-input v-model="assignForm.comment" type="textarea" :disabled="Boolean(busy)"/></el-form-item></el-form><template #footer><el-button :disabled="Boolean(busy)" @click="closeDialog('assign')">取消</el-button><el-button type="primary" :loading="busy==='assign'" :disabled="Boolean(busy)" @click="submitAssign">确认分派</el-button></template></el-dialog>
<el-dialog v-model="repairVisible" title="提交维修结果" width="680px" :close-on-click-modal="!busy" :before-close="()=>closeDialog('repair')"><el-form label-width="105px"><el-form-item label="故障原因"><el-input v-model="repairForm.faultCause" type="textarea" :disabled="Boolean(busy)"/></el-form-item><el-form-item label="维修方案" required><el-input v-model="repairForm.solution" type="textarea" :rows="3" :disabled="Boolean(busy)"/></el-form-item><el-form-item label="使用备件"><el-input v-model="repairForm.partsUsed" :disabled="Boolean(busy)" placeholder="例如：轴承 1 个"/></el-form-item><el-row :gutter="16"><el-col :span="12"><el-form-item label="停机分钟"><el-input-number v-model="repairForm.downtimeMinutes" :min="0" :disabled="Boolean(busy)"/></el-form-item></el-col><el-col :span="12"><el-form-item label="维修费用"><el-input-number v-model="repairForm.maintenanceCost" :min="0" :precision="2" :disabled="Boolean(busy)"/></el-form-item></el-col></el-row><el-form-item label="维修结果" required><el-radio-group v-model="repairForm.result" :disabled="Boolean(busy)"><el-radio-button v-for="x in ['SUCCESS','PARTIAL','FAILED']" :key="x" :value="x">{{displayValue(x)}}</el-radio-button></el-radio-group></el-form-item><el-form-item label="提交说明"><el-input v-model="repairForm.comment" type="textarea" :disabled="Boolean(busy)"/></el-form-item></el-form><template #footer><el-button :disabled="Boolean(busy)" @click="closeDialog('repair')">取消</el-button><el-button type="primary" :loading="busy==='repair-result'" :disabled="Boolean(busy)" @click="submitRepair">提交结果</el-button></template></el-dialog>
<el-dialog v-model="acceptVisible" title="工单验收" width="620px" :close-on-click-modal="!busy" :before-close="()=>closeDialog('accept')"><el-alert title="验收通过将完成工单并把关联缺陷置为已解决；驳回将退回维修中。" type="info" show-icon :closable="false"/><el-form label-width="95px" class="dialog-form"><el-form-item label="验收结果" required><el-radio-group v-model="acceptForm.acceptanceResult" :disabled="Boolean(busy)"><el-radio-button value="PASSED">验收通过</el-radio-button><el-radio-button value="REJECTED">驳回返修</el-radio-button></el-radio-group></el-form-item><el-form-item label="验收说明" required><el-input v-model="acceptForm.acceptanceContent" type="textarea" :rows="3" :disabled="Boolean(busy)"/></el-form-item><el-form-item label="流转备注" :required="acceptForm.acceptanceResult==='REJECTED'"><el-input v-model="acceptForm.comment" type="textarea" :disabled="Boolean(busy)" :placeholder="acceptForm.acceptanceResult==='REJECTED'?'请填写驳回原因':'选填'"/></el-form-item></el-form><template #footer><el-button :disabled="Boolean(busy)" @click="closeDialog('accept')">取消</el-button><el-button type="primary" :loading="busy==='acceptance'" :disabled="Boolean(busy)" @click="submitAccept">提交验收</el-button></template></el-dialog>
</section></template>
<style scoped>.detail-page{display:flex;flex-direction:column;gap:16px}.head-actions{display:flex;gap:10px}.full-card{height:100%}.full-card .el-button{margin-left:8px}.muted{color:var(--el-text-color-secondary);margin-top:6px}.dialog-form{margin-top:18px}.detail-page :deep(.el-dialog .el-select){width:100%}</style>
