<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { useRouter } from 'vue-router';
import { request } from '../api/request';
import { useAuthStore } from '../stores/auth';
import type { Device, PageResult, UserSummary } from '../types/device';
import type { WorkOrder } from '../types/maintenance';
import { displayValue } from '../utils/display';
const router=useRouter(),auth=useAuthStore(),rows=ref<WorkOrder[]>([]),total=ref(0),page=ref(1),loading=ref(false),errorMessage=ref(''),deviceOptions=ref<Device[]>([]),maintainers=ref<UserSummary[]>([]);
const pageSize=20,deviceNames=reactive<Record<string,string>>({}),userNames=reactive<Record<string,string>>({}),defectNames=reactive<Record<string,string>>({}),filters=reactive({status:'',priority:'',deviceId:'',assigneeUserId:''});
const dateTime=(v:string|null)=>v?v.replace('T',' ').slice(0,19):'-',deviceLabel=(d:Device)=>`${d.deviceName}（${d.deviceCode}）`,userLabel=(u:UserSummary)=>u.realName?`${u.realName}（${u.username}）`:u.username;
async function searchDevices(keyword=''){const p=await request.get<never,PageResult<Device>>('/api/device/devices',{params:{pageNum:1,pageSize:20,keyword:keyword||undefined}});deviceOptions.value=p.records??[];deviceOptions.value.forEach(d=>deviceNames[d.id]=deviceLabel(d));}
async function searchMaintainers(keyword=''){if(!auth.can('system:user:view'))return;const p=await request.get<never,PageResult<UserSummary>>('/api/auth/users',{params:{pageNum:1,pageSize:20,keyword:keyword||undefined,status:'ENABLED',roleCode:'MAINTAINER'}});maintainers.value=p.records??[];maintainers.value.forEach(u=>userNames[u.id]=userLabel(u));}
async function resolveRelations(data:WorkOrder[]){await Promise.allSettled([...new Set(data.map(x=>x.deviceId))].filter(id=>!deviceNames[id]).map(async id=>{const d=await request.get<never,Device>(`/api/device/devices/${id}`,{silentStatuses:[404]});deviceNames[id]=deviceLabel(d);}));await Promise.allSettled([...new Set(data.map(x=>x.defectId).filter(Boolean) as string[])].filter(id=>!defectNames[id]).map(async id=>{try{const d=await request.get<never,import('../types/maintenance').Defect>(`/api/maintenance/defects/${id}`,{silentStatuses:[404]});defectNames[id]=`${d.defectCode} · ${d.title}`;}catch(e:any){defectNames[id]=e.response?.status===404?'原缺陷（已不存在）':'缺陷信息暂不可用';}}));if(auth.can('system:user:view'))await Promise.allSettled([...new Set(data.map(x=>x.assigneeUserId).filter(Boolean) as string[])].filter(id=>!userNames[id]).map(async id=>{try{const u=await request.get<never,UserSummary>(`/api/auth/users/${id}`,{silentStatuses:[404]});userNames[id]=userLabel(u);}catch(e:any){userNames[id]=e.response?.status===404?'原维修人员（账号已删除）':'人员信息暂不可用';}}));}
async function load(){loading.value=true;errorMessage.value='';try{const p=await request.get<never,PageResult<WorkOrder>>('/api/maintenance/work-orders',{params:{pageNum:page.value,pageSize,...Object.fromEntries(Object.entries(filters).map(([k,v])=>[k,v||undefined]))}});rows.value=p.records??[];total.value=p.total??0;await resolveRelations(rows.value);}catch{errorMessage.value='维修工单列表加载失败，请稍后重试。';}finally{loading.value=false;}}
function search(){page.value=1;void load()}function reset(){Object.assign(filters,{status:'',priority:'',deviceId:'',assigneeUserId:''});search()}
function assignee(id:string|null){if(!id)return '待分派';if(auth.currentUser?.id===id)return `${auth.currentUser.realName||auth.currentUser.username}（本人）`;return userNames[id]||(auth.can('system:user:view')?'人员信息加载中':'已分派维修人员')}
onMounted(()=>{void searchDevices();void searchMaintainers();void load()});
</script>
<template><section class="business-page"><div class="page-head"><div><h1>维修工单</h1><p>管理员查看并分派全部工单；维修人员仅查看本人负责或本人新建待分派的工单。</p></div></div><el-card shadow="never" class="filter-card"><el-form inline @submit.prevent="search"><el-form-item label="工单状态"><el-select v-model="filters.status" clearable placeholder="全部状态"><el-option v-for="x in ['PENDING','ASSIGNED','PROCESSING','WAITING_ACCEPTANCE','COMPLETED']" :key="x" :label="displayValue(x)" :value="x"/></el-select></el-form-item><el-form-item label="优先级"><el-select v-model="filters.priority" clearable placeholder="全部优先级"><el-option v-for="x in ['LOW','MEDIUM','HIGH','URGENT']" :key="x" :label="displayValue(x)" :value="x"/></el-select></el-form-item><el-form-item label="设备"><el-select v-model="filters.deviceId" filterable remote clearable :remote-method="searchDevices" placeholder="按设备名称或编码搜索"><el-option v-for="d in deviceOptions" :key="d.id" :label="deviceLabel(d)" :value="d.id"/></el-select></el-form-item><el-form-item v-if="auth.can('system:user:view')" label="维修人员"><el-select v-model="filters.assigneeUserId" filterable remote clearable :remote-method="searchMaintainers" placeholder="全部维修人员"><el-option v-for="u in maintainers" :key="u.id" :label="userLabel(u)" :value="u.id"/></el-select></el-form-item><el-form-item><el-button type="primary" @click="search">查询</el-button><el-button @click="reset">重置</el-button></el-form-item></el-form></el-card>
<el-card shadow="never"><el-alert v-if="errorMessage" :title="errorMessage" type="error" show-icon :closable="false"><template #default><el-button link @click="load">重新加载</el-button></template></el-alert><el-table v-else v-loading="loading" :data="rows"><el-table-column prop="workOrderCode" label="工单编号" min-width="180"/><el-table-column prop="title" label="工单标题" min-width="190" show-overflow-tooltip/><el-table-column label="设备" min-width="220"><template #default="s">{{deviceNames[s.row.deviceId]||'设备信息加载中'}}</template></el-table-column><el-table-column label="关联缺陷" min-width="210"><template #default="s">{{s.row.defectId?(defectNames[s.row.defectId]||'缺陷信息加载中'):'无关联缺陷'}}</template></el-table-column><el-table-column label="优先级" width="90"><template #default="s"><el-tag :type="s.row.priority==='URGENT'||s.row.priority==='HIGH'?'danger':'info'">{{displayValue(s.row.priority)}}</el-tag></template></el-table-column><el-table-column label="状态" width="120"><template #default="s"><el-tag>{{displayValue(s.row.status)}}</el-tag></template></el-table-column><el-table-column label="维修人员" min-width="160"><template #default="s">{{assignee(s.row.assigneeUserId)}}</template></el-table-column><el-table-column label="创建时间" min-width="165"><template #default="s">{{dateTime(s.row.createdAt)}}</template></el-table-column><el-table-column label="操作" width="100" fixed="right"><template #default="s"><el-button link type="primary" @click="router.push(`/maintenance/work-orders/${s.row.id}`)">处理工单</el-button></template></el-table-column></el-table><el-empty v-if="!loading&&!errorMessage&&!rows.length" description="暂无符合条件的维修工单"/><el-pagination v-if="!errorMessage&&total>pageSize" v-model:current-page="page" :total="total" :page-size="pageSize" layout="prev, pager, next, total" @current-change="load"/></el-card></section></template>
<style scoped>.business-page{display:flex;flex-direction:column;gap:16px}.filter-card :deep(.el-select){width:210px}.business-page :deep(.el-pagination){justify-content:flex-end;margin-top:18px}</style>
