package com.iiop.ai.domain;

import com.baomidou.mybatisplus.annotation.*;
import com.baomidou.mybatisplus.extension.handlers.JacksonTypeHandler;
import java.time.LocalDateTime;

public final class AiModels {private AiModels(){}
 @TableName(value="ai_diagnosis",autoResultMap=true) public static class Diagnosis {
  @TableId(type=IdType.ASSIGN_ID) private Long id; private String diagnosisCode,triggerType; private Long triggerId,deviceId; private String abnormalSummary,userDescription,riskLevel; @TableField(typeHandler=JacksonTypeHandler.class) private String possibleCauses,investigationSteps,contextSnapshot; private String maintenanceAdvice,safetyNotice,modelName,promptVersion,diagnosisStatus,confirmationStatus; private Long confirmedBy; private LocalDateTime confirmedAt; private String confirmationComment,errorMessage; private LocalDateTime createdAt,updatedAt;
  public Long getId(){return id;}public void setId(Long v){id=v;}public String getDiagnosisCode(){return diagnosisCode;}public void setDiagnosisCode(String v){diagnosisCode=v;}public String getTriggerType(){return triggerType;}public void setTriggerType(String v){triggerType=v;}public Long getTriggerId(){return triggerId;}public void setTriggerId(Long v){triggerId=v;}public Long getDeviceId(){return deviceId;}public void setDeviceId(Long v){deviceId=v;}public String getAbnormalSummary(){return abnormalSummary;}public void setAbnormalSummary(String v){abnormalSummary=v;}public String getUserDescription(){return userDescription;}public void setUserDescription(String v){userDescription=v;}public String getRiskLevel(){return riskLevel;}public void setRiskLevel(String v){riskLevel=v;}public String getPossibleCauses(){return possibleCauses;}public void setPossibleCauses(String v){possibleCauses=v;}public String getInvestigationSteps(){return investigationSteps;}public void setInvestigationSteps(String v){investigationSteps=v;}public String getMaintenanceAdvice(){return maintenanceAdvice;}public void setMaintenanceAdvice(String v){maintenanceAdvice=v;}public String getSafetyNotice(){return safetyNotice;}public void setSafetyNotice(String v){safetyNotice=v;}public String getContextSnapshot(){return contextSnapshot;}public void setContextSnapshot(String v){contextSnapshot=v;}public String getModelName(){return modelName;}public void setModelName(String v){modelName=v;}public String getPromptVersion(){return promptVersion;}public void setPromptVersion(String v){promptVersion=v;}public String getDiagnosisStatus(){return diagnosisStatus;}public void setDiagnosisStatus(String v){diagnosisStatus=v;}public String getConfirmationStatus(){return confirmationStatus;}public void setConfirmationStatus(String v){confirmationStatus=v;}public Long getConfirmedBy(){return confirmedBy;}public void setConfirmedBy(Long v){confirmedBy=v;}public LocalDateTime getConfirmedAt(){return confirmedAt;}public void setConfirmedAt(LocalDateTime v){confirmedAt=v;}public String getConfirmationComment(){return confirmationComment;}public void setConfirmationComment(String v){confirmationComment=v;}public String getErrorMessage(){return errorMessage;}public void setErrorMessage(String v){errorMessage=v;}public LocalDateTime getCreatedAt(){return createdAt;}public void setCreatedAt(LocalDateTime v){createdAt=v;}public LocalDateTime getUpdatedAt(){return updatedAt;}public void setUpdatedAt(LocalDateTime v){updatedAt=v;}
 }
 @TableName(value="ai_workflow_trace",autoResultMap=true) public static class WorkflowTrace {
  @TableId(type=IdType.ASSIGN_ID) private Long id,diagnosisId; private String nodeCode,nodeName,nodeStatus,inputSummary; @TableField(typeHandler=JacksonTypeHandler.class) private String outputData; private String errorMessage; private LocalDateTime startedAt,finishedAt,createdAt;
  public Long getId(){return id;}public void setId(Long v){id=v;}public Long getDiagnosisId(){return diagnosisId;}public void setDiagnosisId(Long v){diagnosisId=v;}public String getNodeCode(){return nodeCode;}public void setNodeCode(String v){nodeCode=v;}public String getNodeName(){return nodeName;}public void setNodeName(String v){nodeName=v;}public String getNodeStatus(){return nodeStatus;}public void setNodeStatus(String v){nodeStatus=v;}public String getInputSummary(){return inputSummary;}public void setInputSummary(String v){inputSummary=v;}public String getOutputData(){return outputData;}public void setOutputData(String v){outputData=v;}public String getErrorMessage(){return errorMessage;}public void setErrorMessage(String v){errorMessage=v;}public LocalDateTime getStartedAt(){return startedAt;}public void setStartedAt(LocalDateTime v){startedAt=v;}public LocalDateTime getFinishedAt(){return finishedAt;}public void setFinishedAt(LocalDateTime v){finishedAt=v;}public LocalDateTime getCreatedAt(){return createdAt;}public void setCreatedAt(LocalDateTime v){createdAt=v;}
 }
}
