package com.iiop.device.domain;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableLogic;
import com.baomidou.mybatisplus.annotation.TableName;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

public final class DeviceModels {
    private DeviceModels(){}
    @TableName("dev_category") public static class Category {
        @TableId(type=IdType.ASSIGN_ID) private Long id; private Long parentId; private String categoryCode; private String categoryName; private String description; private Integer sortOrder; private String status; private LocalDateTime createdAt; private LocalDateTime updatedAt; @TableLogic private Integer deleted;
        public Long getId(){return id;} public void setId(Long v){id=v;} public Long getParentId(){return parentId;} public void setParentId(Long v){parentId=v;} public String getCategoryCode(){return categoryCode;} public void setCategoryCode(String v){categoryCode=v;} public String getCategoryName(){return categoryName;} public void setCategoryName(String v){categoryName=v;} public String getDescription(){return description;} public void setDescription(String v){description=v;} public Integer getSortOrder(){return sortOrder;} public void setSortOrder(Integer v){sortOrder=v;} public String getStatus(){return status;} public void setStatus(String v){status=v;} public LocalDateTime getCreatedAt(){return createdAt;} public void setCreatedAt(LocalDateTime v){createdAt=v;} public LocalDateTime getUpdatedAt(){return updatedAt;} public void setUpdatedAt(LocalDateTime v){updatedAt=v;} public Integer getDeleted(){return deleted;} public void setDeleted(Integer v){deleted=v;}
    }
    @TableName("dev_device") public static class Device {
        @TableId(type=IdType.ASSIGN_ID) private Long id; private String deviceCode; private String deviceName; private Long categoryId; private String model; private String manufacturer; private String serialNumber; private String workshop; private String productionLine; private String installLocation; private Long responsibleUserId; private String status; private String riskLevel; private LocalDate installDate; private LocalDate warrantyExpireDate; private String modelUrl; private BigDecimal positionX; private BigDecimal positionY; private BigDecimal positionZ; private String remark; private LocalDateTime createdAt; private LocalDateTime updatedAt; @TableLogic private Integer deleted;
        public Long getId(){return id;} public void setId(Long v){id=v;} public String getDeviceCode(){return deviceCode;} public void setDeviceCode(String v){deviceCode=v;} public String getDeviceName(){return deviceName;} public void setDeviceName(String v){deviceName=v;} public Long getCategoryId(){return categoryId;} public void setCategoryId(Long v){categoryId=v;} public String getModel(){return model;} public void setModel(String v){model=v;} public String getManufacturer(){return manufacturer;} public void setManufacturer(String v){manufacturer=v;} public String getSerialNumber(){return serialNumber;} public void setSerialNumber(String v){serialNumber=v;} public String getWorkshop(){return workshop;} public void setWorkshop(String v){workshop=v;} public String getProductionLine(){return productionLine;} public void setProductionLine(String v){productionLine=v;} public String getInstallLocation(){return installLocation;} public void setInstallLocation(String v){installLocation=v;} public Long getResponsibleUserId(){return responsibleUserId;} public void setResponsibleUserId(Long v){responsibleUserId=v;} public String getStatus(){return status;} public void setStatus(String v){status=v;} public String getRiskLevel(){return riskLevel;} public void setRiskLevel(String v){riskLevel=v;} public LocalDate getInstallDate(){return installDate;} public void setInstallDate(LocalDate v){installDate=v;} public LocalDate getWarrantyExpireDate(){return warrantyExpireDate;} public void setWarrantyExpireDate(LocalDate v){warrantyExpireDate=v;} public String getModelUrl(){return modelUrl;} public void setModelUrl(String v){modelUrl=v;} public BigDecimal getPositionX(){return positionX;} public void setPositionX(BigDecimal v){positionX=v;} public BigDecimal getPositionY(){return positionY;} public void setPositionY(BigDecimal v){positionY=v;} public BigDecimal getPositionZ(){return positionZ;} public void setPositionZ(BigDecimal v){positionZ=v;} public String getRemark(){return remark;} public void setRemark(String v){remark=v;} public LocalDateTime getCreatedAt(){return createdAt;} public void setCreatedAt(LocalDateTime v){createdAt=v;} public LocalDateTime getUpdatedAt(){return updatedAt;} public void setUpdatedAt(LocalDateTime v){updatedAt=v;} public Integer getDeleted(){return deleted;} public void setDeleted(Integer v){deleted=v;}
    }
    @TableName("dev_metric") public static class Metric {
        @TableId(type=IdType.ASSIGN_ID) private Long id; private Long deviceId; private String metricCode; private String metricName; private String unit; private String valueType; private BigDecimal warningLow; private BigDecimal warningHigh; private BigDecimal criticalLow; private BigDecimal criticalHigh; private String status; private LocalDateTime createdAt; private LocalDateTime updatedAt; @TableLogic private Integer deleted;
        public Long getId(){return id;} public void setId(Long v){id=v;} public Long getDeviceId(){return deviceId;} public void setDeviceId(Long v){deviceId=v;} public String getMetricCode(){return metricCode;} public void setMetricCode(String v){metricCode=v;} public String getMetricName(){return metricName;} public void setMetricName(String v){metricName=v;} public String getUnit(){return unit;} public void setUnit(String v){unit=v;} public String getValueType(){return valueType;} public void setValueType(String v){valueType=v;} public BigDecimal getWarningLow(){return warningLow;} public void setWarningLow(BigDecimal v){warningLow=v;} public BigDecimal getWarningHigh(){return warningHigh;} public void setWarningHigh(BigDecimal v){warningHigh=v;} public BigDecimal getCriticalLow(){return criticalLow;} public void setCriticalLow(BigDecimal v){criticalLow=v;} public BigDecimal getCriticalHigh(){return criticalHigh;} public void setCriticalHigh(BigDecimal v){criticalHigh=v;} public String getStatus(){return status;} public void setStatus(String v){status=v;} public LocalDateTime getCreatedAt(){return createdAt;} public void setCreatedAt(LocalDateTime v){createdAt=v;} public LocalDateTime getUpdatedAt(){return updatedAt;} public void setUpdatedAt(LocalDateTime v){updatedAt=v;} public Integer getDeleted(){return deleted;} public void setDeleted(Integer v){deleted=v;}
    }
    @TableName("dev_metric_data") public static class MetricData {
        @TableId(type=IdType.ASSIGN_ID) private Long id; private Long deviceId; private Long metricId; private BigDecimal numericValue; private String textValue; private Integer booleanValue; private String quality; private LocalDateTime collectTime; private LocalDateTime createdAt;
        public Long getId(){return id;} public void setId(Long v){id=v;} public Long getDeviceId(){return deviceId;} public void setDeviceId(Long v){deviceId=v;} public Long getMetricId(){return metricId;} public void setMetricId(Long v){metricId=v;} public BigDecimal getNumericValue(){return numericValue;} public void setNumericValue(BigDecimal v){numericValue=v;} public String getTextValue(){return textValue;} public void setTextValue(String v){textValue=v;} public Integer getBooleanValue(){return booleanValue;} public void setBooleanValue(Integer v){booleanValue=v;} public String getQuality(){return quality;} public void setQuality(String v){quality=v;} public LocalDateTime getCollectTime(){return collectTime;} public void setCollectTime(LocalDateTime v){collectTime=v;} public LocalDateTime getCreatedAt(){return createdAt;} public void setCreatedAt(LocalDateTime v){createdAt=v;}
    }
    @TableName("dev_sop") public static class Sop {
        @TableId(type=IdType.ASSIGN_ID) private Long id; private String sopCode; private String title; private Long categoryId; private Long deviceId; private String sopType; private String version; private String content; private String status; private LocalDate effectiveDate; private LocalDateTime createdAt; private LocalDateTime updatedAt; @TableLogic private Integer deleted;
        public Long getId(){return id;} public void setId(Long v){id=v;} public String getSopCode(){return sopCode;} public void setSopCode(String v){sopCode=v;} public String getTitle(){return title;} public void setTitle(String v){title=v;} public Long getCategoryId(){return categoryId;} public void setCategoryId(Long v){categoryId=v;} public Long getDeviceId(){return deviceId;} public void setDeviceId(Long v){deviceId=v;} public String getSopType(){return sopType;} public void setSopType(String v){sopType=v;} public String getVersion(){return version;} public void setVersion(String v){version=v;} public String getContent(){return content;} public void setContent(String v){content=v;} public String getStatus(){return status;} public void setStatus(String v){status=v;} public LocalDate getEffectiveDate(){return effectiveDate;} public void setEffectiveDate(LocalDate v){effectiveDate=v;} public LocalDateTime getCreatedAt(){return createdAt;} public void setCreatedAt(LocalDateTime v){createdAt=v;} public LocalDateTime getUpdatedAt(){return updatedAt;} public void setUpdatedAt(LocalDateTime v){updatedAt=v;} public Integer getDeleted(){return deleted;} public void setDeleted(Integer v){deleted=v;}
    }
}
