package com.iiop.inspection.domain;

import com.baomidou.mybatisplus.annotation.*;
import com.baomidou.mybatisplus.extension.handlers.JacksonTypeHandler;
import java.math.BigDecimal;
import java.time.*;

public final class InspectionModels {private InspectionModels(){}
    @TableName(value="ins_template",autoResultMap=true) public static class Template {
        @TableId(type=IdType.ASSIGN_ID) private Long id;private String templateCode;private String templateName;private Long categoryId;private Integer version;private String description;@TableField(typeHandler=JacksonTypeHandler.class) private String flowDefinition;private String status;private LocalDateTime createdAt;private LocalDateTime updatedAt;@TableLogic private Integer deleted;
        public Long getId(){return id;}public void setId(Long v){id=v;}public String getTemplateCode(){return templateCode;}public void setTemplateCode(String v){templateCode=v;}public String getTemplateName(){return templateName;}public void setTemplateName(String v){templateName=v;}public Long getCategoryId(){return categoryId;}public void setCategoryId(Long v){categoryId=v;}public Integer getVersion(){return version;}public void setVersion(Integer v){version=v;}public String getDescription(){return description;}public void setDescription(String v){description=v;}public String getFlowDefinition(){return flowDefinition;}public void setFlowDefinition(String v){flowDefinition=v;}public String getStatus(){return status;}public void setStatus(String v){status=v;}public LocalDateTime getCreatedAt(){return createdAt;}public void setCreatedAt(LocalDateTime v){createdAt=v;}public LocalDateTime getUpdatedAt(){return updatedAt;}public void setUpdatedAt(LocalDateTime v){updatedAt=v;}public Integer getDeleted(){return deleted;}public void setDeleted(Integer v){deleted=v;}
    }
    @TableName("ins_template_item") public static class TemplateItem {
        @TableId(type=IdType.ASSIGN_ID) private Long id;private Long templateId;private String itemCode;private String itemName;private String itemType;private String unit;private String standardValue;private BigDecimal lowerLimit;private BigDecimal upperLimit;private Integer requiredFlag;private Integer sortOrder;private String inspectionMethod;private String abnormalHint;private LocalDateTime createdAt;private LocalDateTime updatedAt;@TableLogic private Integer deleted;
        public Long getId(){return id;}public void setId(Long v){id=v;}public Long getTemplateId(){return templateId;}public void setTemplateId(Long v){templateId=v;}public String getItemCode(){return itemCode;}public void setItemCode(String v){itemCode=v;}public String getItemName(){return itemName;}public void setItemName(String v){itemName=v;}public String getItemType(){return itemType;}public void setItemType(String v){itemType=v;}public String getUnit(){return unit;}public void setUnit(String v){unit=v;}public String getStandardValue(){return standardValue;}public void setStandardValue(String v){standardValue=v;}public BigDecimal getLowerLimit(){return lowerLimit;}public void setLowerLimit(BigDecimal v){lowerLimit=v;}public BigDecimal getUpperLimit(){return upperLimit;}public void setUpperLimit(BigDecimal v){upperLimit=v;}public Integer getRequiredFlag(){return requiredFlag;}public void setRequiredFlag(Integer v){requiredFlag=v;}public Integer getSortOrder(){return sortOrder;}public void setSortOrder(Integer v){sortOrder=v;}public String getInspectionMethod(){return inspectionMethod;}public void setInspectionMethod(String v){inspectionMethod=v;}public String getAbnormalHint(){return abnormalHint;}public void setAbnormalHint(String v){abnormalHint=v;}public LocalDateTime getCreatedAt(){return createdAt;}public void setCreatedAt(LocalDateTime v){createdAt=v;}public LocalDateTime getUpdatedAt(){return updatedAt;}public void setUpdatedAt(LocalDateTime v){updatedAt=v;}public Integer getDeleted(){return deleted;}public void setDeleted(Integer v){deleted=v;}
    }
    @TableName("ins_plan") public static class Plan {
        @TableId(type=IdType.ASSIGN_ID) private Long id;private String planCode;private String planName;private Long deviceId;private Long templateId;private String scheduleType;private String cronExpression;private LocalDate startDate;private LocalDate endDate;private Long assigneeUserId;private String status;private LocalDateTime lastGenerateTime;private LocalDateTime nextGenerateTime;private LocalDateTime createdAt;private LocalDateTime updatedAt;@TableLogic private Integer deleted;
        public Long getId(){return id;}public void setId(Long v){id=v;}public String getPlanCode(){return planCode;}public void setPlanCode(String v){planCode=v;}public String getPlanName(){return planName;}public void setPlanName(String v){planName=v;}public Long getDeviceId(){return deviceId;}public void setDeviceId(Long v){deviceId=v;}public Long getTemplateId(){return templateId;}public void setTemplateId(Long v){templateId=v;}public String getScheduleType(){return scheduleType;}public void setScheduleType(String v){scheduleType=v;}public String getCronExpression(){return cronExpression;}public void setCronExpression(String v){cronExpression=v;}public LocalDate getStartDate(){return startDate;}public void setStartDate(LocalDate v){startDate=v;}public LocalDate getEndDate(){return endDate;}public void setEndDate(LocalDate v){endDate=v;}public Long getAssigneeUserId(){return assigneeUserId;}public void setAssigneeUserId(Long v){assigneeUserId=v;}public String getStatus(){return status;}public void setStatus(String v){status=v;}public LocalDateTime getLastGenerateTime(){return lastGenerateTime;}public void setLastGenerateTime(LocalDateTime v){lastGenerateTime=v;}public LocalDateTime getNextGenerateTime(){return nextGenerateTime;}public void setNextGenerateTime(LocalDateTime v){nextGenerateTime=v;}public LocalDateTime getCreatedAt(){return createdAt;}public void setCreatedAt(LocalDateTime v){createdAt=v;}public LocalDateTime getUpdatedAt(){return updatedAt;}public void setUpdatedAt(LocalDateTime v){updatedAt=v;}public Integer getDeleted(){return deleted;}public void setDeleted(Integer v){deleted=v;}
    }
    @TableName("ins_task") public static class Task {
        @TableId(type=IdType.ASSIGN_ID) private Long id;private String taskCode;private Long planId;private Long deviceId;private Long templateId;private Long assigneeUserId;private String taskStatus;private Integer overdueFlag;private String resultStatus;private LocalDateTime scheduledStartTime;private LocalDateTime scheduledEndTime;private LocalDateTime actualStartTime;private LocalDateTime actualEndTime;private BigDecimal completionRate;private String remark;private LocalDateTime createdAt;private LocalDateTime updatedAt;
        public Long getId(){return id;}public void setId(Long v){id=v;}public String getTaskCode(){return taskCode;}public void setTaskCode(String v){taskCode=v;}public Long getPlanId(){return planId;}public void setPlanId(Long v){planId=v;}public Long getDeviceId(){return deviceId;}public void setDeviceId(Long v){deviceId=v;}public Long getTemplateId(){return templateId;}public void setTemplateId(Long v){templateId=v;}public Long getAssigneeUserId(){return assigneeUserId;}public void setAssigneeUserId(Long v){assigneeUserId=v;}public String getTaskStatus(){return taskStatus;}public void setTaskStatus(String v){taskStatus=v;}public Integer getOverdueFlag(){return overdueFlag;}public void setOverdueFlag(Integer v){overdueFlag=v;}public String getResultStatus(){return resultStatus;}public void setResultStatus(String v){resultStatus=v;}public LocalDateTime getScheduledStartTime(){return scheduledStartTime;}public void setScheduledStartTime(LocalDateTime v){scheduledStartTime=v;}public LocalDateTime getScheduledEndTime(){return scheduledEndTime;}public void setScheduledEndTime(LocalDateTime v){scheduledEndTime=v;}public LocalDateTime getActualStartTime(){return actualStartTime;}public void setActualStartTime(LocalDateTime v){actualStartTime=v;}public LocalDateTime getActualEndTime(){return actualEndTime;}public void setActualEndTime(LocalDateTime v){actualEndTime=v;}public BigDecimal getCompletionRate(){return completionRate;}public void setCompletionRate(BigDecimal v){completionRate=v;}public String getRemark(){return remark;}public void setRemark(String v){remark=v;}public LocalDateTime getCreatedAt(){return createdAt;}public void setCreatedAt(LocalDateTime v){createdAt=v;}public LocalDateTime getUpdatedAt(){return updatedAt;}public void setUpdatedAt(LocalDateTime v){updatedAt=v;}
    }
    @TableName(value="ins_task_item",autoResultMap=true) public static class TaskItem {
        @TableId(type=IdType.ASSIGN_ID) private Long id;private Long taskId;private Long templateItemId;private String itemCode;private String itemName;private String itemType;private String unit;private String standardValue;private BigDecimal lowerLimit;private BigDecimal upperLimit;private Integer requiredFlag;private String inspectionMethod;private String actualValue;private String resultStatus;private String remark;@TableField(typeHandler=JacksonTypeHandler.class) private String evidenceUrls;private Integer sortOrder;private LocalDateTime checkedAt;private LocalDateTime createdAt;private LocalDateTime updatedAt;
        public Long getId(){return id;}public void setId(Long v){id=v;}public Long getTaskId(){return taskId;}public void setTaskId(Long v){taskId=v;}public Long getTemplateItemId(){return templateItemId;}public void setTemplateItemId(Long v){templateItemId=v;}public String getItemCode(){return itemCode;}public void setItemCode(String v){itemCode=v;}public String getItemName(){return itemName;}public void setItemName(String v){itemName=v;}public String getItemType(){return itemType;}public void setItemType(String v){itemType=v;}public String getUnit(){return unit;}public void setUnit(String v){unit=v;}public String getStandardValue(){return standardValue;}public void setStandardValue(String v){standardValue=v;}public BigDecimal getLowerLimit(){return lowerLimit;}public void setLowerLimit(BigDecimal v){lowerLimit=v;}public BigDecimal getUpperLimit(){return upperLimit;}public void setUpperLimit(BigDecimal v){upperLimit=v;}public Integer getRequiredFlag(){return requiredFlag;}public void setRequiredFlag(Integer v){requiredFlag=v;}public String getInspectionMethod(){return inspectionMethod;}public void setInspectionMethod(String v){inspectionMethod=v;}public String getActualValue(){return actualValue;}public void setActualValue(String v){actualValue=v;}public String getResultStatus(){return resultStatus;}public void setResultStatus(String v){resultStatus=v;}public String getRemark(){return remark;}public void setRemark(String v){remark=v;}public String getEvidenceUrls(){return evidenceUrls;}public void setEvidenceUrls(String v){evidenceUrls=v;}public Integer getSortOrder(){return sortOrder;}public void setSortOrder(Integer v){sortOrder=v;}public LocalDateTime getCheckedAt(){return checkedAt;}public void setCheckedAt(LocalDateTime v){checkedAt=v;}public LocalDateTime getCreatedAt(){return createdAt;}public void setCreatedAt(LocalDateTime v){createdAt=v;}public LocalDateTime getUpdatedAt(){return updatedAt;}public void setUpdatedAt(LocalDateTime v){updatedAt=v;}
    }
    @TableName(value="ins_abnormal",autoResultMap=true) public static class Abnormal {
        @TableId(type=IdType.ASSIGN_ID) private Long id;private String abnormalCode;private Long taskId;private Long taskItemId;private Long deviceId;private String abnormalType;private String severity;private String title;private String description;@TableField(typeHandler=JacksonTypeHandler.class) private String evidenceUrls;private Long reportedBy;private LocalDateTime reportedAt;private String status;private Long aiDiagnosisId;private LocalDateTime resolvedAt;private LocalDateTime createdAt;private LocalDateTime updatedAt;
        public Long getId(){return id;}public void setId(Long v){id=v;}public String getAbnormalCode(){return abnormalCode;}public void setAbnormalCode(String v){abnormalCode=v;}public Long getTaskId(){return taskId;}public void setTaskId(Long v){taskId=v;}public Long getTaskItemId(){return taskItemId;}public void setTaskItemId(Long v){taskItemId=v;}public Long getDeviceId(){return deviceId;}public void setDeviceId(Long v){deviceId=v;}public String getAbnormalType(){return abnormalType;}public void setAbnormalType(String v){abnormalType=v;}public String getSeverity(){return severity;}public void setSeverity(String v){severity=v;}public String getTitle(){return title;}public void setTitle(String v){title=v;}public String getDescription(){return description;}public void setDescription(String v){description=v;}public String getEvidenceUrls(){return evidenceUrls;}public void setEvidenceUrls(String v){evidenceUrls=v;}public Long getReportedBy(){return reportedBy;}public void setReportedBy(Long v){reportedBy=v;}public LocalDateTime getReportedAt(){return reportedAt;}public void setReportedAt(LocalDateTime v){reportedAt=v;}public String getStatus(){return status;}public void setStatus(String v){status=v;}public Long getAiDiagnosisId(){return aiDiagnosisId;}public void setAiDiagnosisId(Long v){aiDiagnosisId=v;}public LocalDateTime getResolvedAt(){return resolvedAt;}public void setResolvedAt(LocalDateTime v){resolvedAt=v;}public LocalDateTime getCreatedAt(){return createdAt;}public void setCreatedAt(LocalDateTime v){createdAt=v;}public LocalDateTime getUpdatedAt(){return updatedAt;}public void setUpdatedAt(LocalDateTime v){updatedAt=v;}
    }
}
