package com.iiop.ai.service;
import feign.FeignException;
import cn.dev33.satoken.stp.StpUtil;import com.baomidou.mybatisplus.core.toolkit.Wrappers;import com.fasterxml.jackson.databind.ObjectMapper;import com.iiop.ai.client.AiClients.*;import com.iiop.ai.domain.AiDtos.*;import com.iiop.ai.domain.AiModels.*;import com.iiop.ai.mapper.AiDiagnosisMapper;import com.iiop.ai.workflow.*;import com.iiop.common.api.*;import com.iiop.common.exception.BizException;import java.time.LocalDateTime;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class AiDiagnosisService {
 private static final Set<String>TYPES=Set.of("INSPECTION_ABNORMAL","ALARM","MANUAL");private final AiDiagnosisMapper diagnoses;private final AiPersistenceService persistence;private final AiWorkflow workflow;private final ObjectMapper json;private final InspectionClient inspection;
 public AiDiagnosisService(AiDiagnosisMapper d,AiPersistenceService p,AiWorkflow w,ObjectMapper j,InspectionClient i){diagnoses=d;persistence=p;workflow=w;json=j;inspection=i;}
 public DiagnosisView create(CreateRequest r){validateRequest(r);validateInspectorTrigger(r);if(!"MANUAL".equals(r.triggerType())&&diagnoses.selectCount(Wrappers.<Diagnosis>lambdaQuery().eq(Diagnosis::getTriggerType,r.triggerType()).eq(Diagnosis::getTriggerId,r.triggerId()))>0)throw conflict("该触发对象已存在诊断");Diagnosis d=new Diagnosis();d.setDiagnosisCode("AI"+System.currentTimeMillis());d.setTriggerType(r.triggerType());d.setTriggerId(r.triggerId());d.setDeviceId(r.deviceId());d.setAbnormalSummary(blank(r.abnormalSummary())?"待加载异常摘要":r.abnormalSummary());d.setUserDescription(r.userDescription());d.setDiagnosisStatus("PENDING");d.setConfirmationStatus("PENDING");d.setPromptVersion("iiop-diagnosis-v1");d.setCreatedAt(LocalDateTime.now());persistence.create(d);persistence.markRunning(d.getId());try{WorkflowData result=workflow.execute(d,new WorkflowInput(r.triggerType(),r.triggerId(),r.deviceId(),r.abnormalSummary(),r.userDescription()));applySuccess(d,result);persistence.finish(d);return view(d);}catch(Exception e){return view(require(d.getId()));}}
 public PageResult<Diagnosis> list(long page,long size,String triggerType,Long triggerId,Long deviceId,String diagnosisStatus,String riskLevel,String confirmationStatus){var q=Wrappers.<Diagnosis>lambdaQuery().eq(triggerType!=null,Diagnosis::getTriggerType,triggerType).eq(triggerId!=null,Diagnosis::getTriggerId,triggerId).eq(deviceId!=null,Diagnosis::getDeviceId,deviceId).eq(diagnosisStatus!=null,Diagnosis::getDiagnosisStatus,diagnosisStatus).eq(riskLevel!=null,Diagnosis::getRiskLevel,riskLevel).eq(confirmationStatus!=null,Diagnosis::getConfirmationStatus,confirmationStatus);if(restrictedInspector()){List<Long>ids=ownedIds();if(ids.isEmpty())return new PageResult<>(page,Math.min(size,100),0,List.of());q.eq(Diagnosis::getTriggerType,"INSPECTION_ABNORMAL").in(Diagnosis::getTriggerId,ids);}var p=diagnoses.selectPage(new com.baomidou.mybatisplus.extension.plugins.pagination.Page<Diagnosis>(page,Math.min(size,100)),q.orderByDesc(Diagnosis::getCreatedAt));return new PageResult<>(p.getCurrent(),p.getSize(),p.getTotal(),p.getRecords());}
 public DiagnosisView detail(Long id){Diagnosis d=require(id);visible(d);return view(d);}public List<WorkflowTrace> workflow(Long id){Diagnosis d=require(id);visible(d);return persistence.traces(id);}public DiagnosisSummary summary(Long id){Diagnosis d=require(id);return new DiagnosisSummary(d.getId(),d.getTriggerType(),d.getTriggerId(),d.getDeviceId(),d.getDiagnosisStatus(),d.getConfirmationStatus(),d.getRiskLevel());}
 @Transactional public DiagnosisView confirm(Long id,String comment,boolean accepted){require(id);if(!accepted&&blank(comment))throw bad("拒绝原因必填");int n=diagnoses.update(null,Wrappers.<Diagnosis>lambdaUpdate().eq(Diagnosis::getId,id).eq(Diagnosis::getDiagnosisStatus,"SUCCEEDED").eq(Diagnosis::getConfirmationStatus,"PENDING").set(Diagnosis::getConfirmationStatus,accepted?"CONFIRMED":"REJECTED").set(Diagnosis::getConfirmedBy,StpUtil.getLoginIdAsLong()).set(Diagnosis::getConfirmedAt,LocalDateTime.now()).set(Diagnosis::getConfirmationComment,comment));if(n!=1)throw conflict("诊断状态已变化");return view(require(id));}
 private void validateRequest(CreateRequest r){if(!TYPES.contains(r.triggerType()))throw bad("触发类型不正确");if(r.deviceId()==null)throw bad("deviceId 必填");if("MANUAL".equals(r.triggerType())){if(r.triggerId()!=null||blank(r.abnormalSummary()))throw bad("MANUAL 诊断需要异常摘要且不能传 triggerId");}else if(r.triggerId()==null)throw bad("非 MANUAL 诊断需要 triggerId");}
 private boolean restrictedInspector(){return StpUtil.hasRole("INSPECTOR")&&!StpUtil.hasRole("ADMIN")&&!StpUtil.hasRole("SUPER_ADMIN")&&!StpUtil.hasRole("MAINTAINER");}private void validateInspectorTrigger(CreateRequest r){if(!restrictedInspector())return;if(!"INSPECTION_ABNORMAL".equals(r.triggerType()))throw forbidden("巡检员只能诊断本人巡检异常");AbnormalDto a=abnormal(r.triggerId());if(!Objects.equals(a.assigneeUserId(),StpUtil.getLoginIdAsLong())||!Objects.equals(a.deviceId(),r.deviceId()))throw forbidden("只能诊断本人巡检异常");}private void visible(Diagnosis d){if(!restrictedInspector())return;if(!"INSPECTION_ABNORMAL".equals(d.getTriggerType())||!Objects.equals(abnormal(d.getTriggerId()).assigneeUserId(),StpUtil.getLoginIdAsLong()))throw forbidden("无权查看该诊断");}
 private AbnormalDto abnormal(Long id){try{Result<AbnormalDto>r=inspection.abnormal(id);if(r==null||r.code()!=0||r.data()==null)throw new BizException(ErrorCode.NOT_FOUND,"巡检异常不存在");return r.data();}catch(BizException e){throw e;}catch(FeignException.NotFound e){throw new BizException(ErrorCode.NOT_FOUND,"巡检异常不存在");}catch(FeignException e){throw new BizException(ErrorCode.SERVICE_UNAVAILABLE,"巡检服务不可用");}}private List<Long>ownedIds(){try{Result<List<Long>>r=inspection.abnormalIds(StpUtil.getLoginIdAsLong());return r==null||r.code()!=0||r.data()==null?List.of():r.data();}catch(FeignException e){throw new BizException(ErrorCode.SERVICE_UNAVAILABLE,"巡检服务不可用");}}
 private void applySuccess(Diagnosis d,WorkflowData r){ModelResult m=r.model;d.setRiskLevel(r.risk);d.setAbnormalSummary(m.abnormalSummary());d.setPossibleCauses(m.possibleCauses());d.setInvestigationSteps(m.investigationSteps());d.setMaintenanceAdvice(m.maintenanceAdvice());d.setSafetyNotice(m.safetyNotice());d.setContextSnapshot(r.context);d.setModelName(workflow.modelName());d.setDiagnosisStatus("SUCCEEDED");d.setConfirmationStatus("PENDING");d.setErrorMessage(null);}private Diagnosis require(Long id){Diagnosis d=diagnoses.selectById(id);if(d==null)throw new BizException(ErrorCode.NOT_FOUND,"AI 诊断不存在");return d;}
 private DiagnosisView view(Diagnosis d){WorkOrderDraft draft=null;for(WorkflowTrace t:persistence.traces(d.getId()))if("PREPARE_WORK_ORDER_DRAFT".equals(t.getNodeCode())&&"SUCCEEDED".equals(t.getNodeStatus())&&t.getOutputData()!=null)try{draft=json.readValue(t.getOutputData(),WorkOrderDraft.class);}catch(Exception ignored){}return new DiagnosisView(d,d.getPossibleCauses()==null?List.of():d.getPossibleCauses(),d.getInvestigationSteps()==null?List.of():d.getInvestigationSteps(),draft,AiWorkflow.requiresConfirmation(d.getRiskLevel()));}private boolean blank(String v){return v==null||v.isBlank();}private BizException bad(String m){return new BizException(ErrorCode.BAD_REQUEST,m);}private BizException conflict(String m){return new BizException(ErrorCode.CONFLICT,m);}private BizException forbidden(String m){return new BizException(ErrorCode.FORBIDDEN,m);}
}
