package com.iiop.ai.service;

import cn.dev33.satoken.stp.StpUtil;
import com.baomidou.mybatisplus.core.toolkit.Wrappers;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.iiop.ai.client.AiClients.*;
import com.iiop.ai.domain.AiDtos.*;
import com.iiop.ai.domain.AiModels.*;
import com.iiop.ai.mapper.AiDiagnosisMapper;
import com.iiop.ai.workflow.*;
import com.iiop.common.api.*;
import com.iiop.common.exception.BizException;
import java.time.LocalDateTime;
import java.util.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service public class AiDiagnosisService {
 private static final Set<String> TYPES=Set.of("INSPECTION_ABNORMAL","ALARM","MANUAL");private final AiDiagnosisMapper diagnoses;private final AiPersistenceService persistence;private final AiWorkflow workflow;private final DeviceClient devices;private final InspectionClient inspection;private final MaintenanceClient maintenance;private final ObjectMapper json;
 public AiDiagnosisService(AiDiagnosisMapper d,AiPersistenceService p,AiWorkflow w,DeviceClient dc,InspectionClient ic,MaintenanceClient mc,ObjectMapper j){diagnoses=d;persistence=p;workflow=w;devices=dc;inspection=ic;maintenance=mc;json=j;}
 public DiagnosisView create(CreateRequest request){if(!TYPES.contains(request.triggerType()))throw bad("触发类型不正确");Source source=source(request);if(!"MANUAL".equals(request.triggerType())&&diagnoses.selectCount(Wrappers.<Diagnosis>lambdaQuery().eq(Diagnosis::getTriggerType,request.triggerType()).eq(Diagnosis::getTriggerId,request.triggerId()))>0)throw new BizException(ErrorCode.CONFLICT,"该触发对象已存在诊断");Diagnosis d=new Diagnosis();d.setDiagnosisCode("AI"+System.currentTimeMillis());d.setTriggerType(request.triggerType());d.setTriggerId(request.triggerId());d.setDeviceId(source.deviceId);d.setAbnormalSummary(source.summary);d.setUserDescription(request.userDescription());d.setDiagnosisStatus("RUNNING");d.setConfirmationStatus("PENDING");d.setPromptVersion("v1");d.setCreatedAt(LocalDateTime.now());persistence.create(d);try{Map<String,Object> context=loadContext(source);WorkflowData result=workflow.execute(d,context);applySuccess(d,result);persistence.finish(d);return view(d);}catch(Exception e){return view(require(d.getId()));}}
 public PageResult<Diagnosis> list(long page,long size){var p=diagnoses.selectPage(new com.baomidou.mybatisplus.extension.plugins.pagination.Page<Diagnosis>(page,Math.min(size,100)),Wrappers.<Diagnosis>lambdaQuery().orderByDesc(Diagnosis::getCreatedAt));return new PageResult<>(p.getCurrent(),p.getSize(),p.getTotal(),p.getRecords());}
 public DiagnosisView detail(Long id){return view(require(id));}public List<WorkflowTrace> workflow(Long id){require(id);return persistence.traces(id);}
 @Transactional public DiagnosisView confirm(Long id,String comment,boolean accepted){Diagnosis d=require(id);if(!"SUCCEEDED".equals(d.getDiagnosisStatus()))throw new BizException(ErrorCode.CONFLICT,"诊断尚未成功");if(!"PENDING".equals(d.getConfirmationStatus()))throw new BizException(ErrorCode.CONFLICT,"诊断已确认或已拒绝");d.setConfirmationStatus(accepted?"CONFIRMED":"REJECTED");d.setConfirmedBy(StpUtil.getLoginIdAsLong());d.setConfirmedAt(LocalDateTime.now());d.setConfirmationComment(comment);diagnoses.updateById(d);return view(d);}
 private Source source(CreateRequest r){if("MANUAL".equals(r.triggerType())){if(r.triggerId()!=null||r.deviceId()==null||blank(r.abnormalSummary()))throw bad("MANUAL 诊断需要设备和异常摘要，且不能传 triggerId");return new Source(r.deviceId(),r.abnormalSummary(),"LOW",Map.of("triggerType","MANUAL"));}if(r.triggerId()==null||r.deviceId()==null)throw bad("非 MANUAL 诊断需要 triggerId 和 deviceId");if("INSPECTION_ABNORMAL".equals(r.triggerType())){var a=body(inspection.abnormal(r.triggerId()),"巡检异常不存在");if(!Objects.equals(a.deviceId(),r.deviceId()))throw bad("异常与设备不匹配");return new Source(a.deviceId(),join(a.title(),a.description()),a.severity(),Map.of("trigger",a));}var a=body(maintenance.alarm(r.triggerId()),"告警不存在");if(!Objects.equals(a.deviceId(),r.deviceId()))throw bad("告警与设备不匹配");return new Source(a.deviceId(),join(a.alarmTitle(),a.alarmContent()),alarmRisk(a.alarmLevel()),Map.of("trigger",a));}
 private Map<String,Object> loadContext(Source s){Map<String,Object> c=new LinkedHashMap<>();c.putAll(s.trigger);c.put("triggerRisk",s.risk);try{c.put("device",body(devices.context(s.deviceId),"设备上下文不可用"));c.put("sop",body(devices.sop(s.deviceId),"SOP 上下文不可用"));}catch(Exception e){throw new IllegalStateException("设备上下文加载失败",e);}try{c.put("inspectionHistory",body(inspection.history(s.deviceId),""));}catch(Exception e){c.put("inspectionHistory",Map.of());}try{c.put("maintenanceHistory",body(maintenance.history(s.deviceId),""));}catch(Exception e){c.put("maintenanceHistory",Map.of());}return c;}
 private void applySuccess(Diagnosis d,WorkflowData r){ModelResult m=r.model;d.setRiskLevel(r.risk);d.setAbnormalSummary(m.abnormalSummary());d.setPossibleCauses(write(m.possibleCauses()));d.setInvestigationSteps(write(m.investigationSteps()));d.setMaintenanceAdvice(m.maintenanceAdvice());d.setSafetyNotice(m.safetyNotice());d.setContextSnapshot(write(r.context));d.setModelName(workflow.modelName());d.setDiagnosisStatus("SUCCEEDED");d.setConfirmationStatus("PENDING");d.setErrorMessage(null);}
 private Diagnosis require(Long id){Diagnosis d=diagnoses.selectById(id);if(d==null)throw new BizException(ErrorCode.NOT_FOUND,"AI 诊断不存在");return d;}private DiagnosisView view(Diagnosis d){return new DiagnosisView(d,read(d.getPossibleCauses()),read(d.getInvestigationSteps()),null);}private <T>T body(Result<T> r,String msg){if(r==null||r.code()!=0||r.data()==null)throw new BizException(ErrorCode.NOT_FOUND,msg);return r.data();}private String write(Object v){try{return json.writeValueAsString(v);}catch(Exception e){throw new IllegalStateException(e);}}private List<String> read(String v){try{return v==null?List.of():json.readValue(v,new TypeReference<List<String>>(){});}catch(Exception e){return List.of();}}private String alarmRisk(String v){return Map.of("INFO","LOW","WARNING","MEDIUM","MAJOR","HIGH","CRITICAL","CRITICAL").getOrDefault(v,"LOW");}private String join(String a,String b){return (a==null?"":a)+(b==null?"":"："+b);}private boolean blank(String v){return v==null||v.isBlank();}private BizException bad(String m){return new BizException(ErrorCode.BAD_REQUEST,m);}private record Source(Long deviceId,String summary,String risk,Map<String,Object> trigger){}
}
