package com.iiop.ai.service;
import feign.FeignException;
import cn.dev33.satoken.stp.StpUtil;import com.baomidou.mybatisplus.core.toolkit.Wrappers;import com.fasterxml.jackson.databind.ObjectMapper;import com.iiop.ai.client.AiClients.*;import com.iiop.ai.domain.AiDtos.*;import com.iiop.ai.domain.AiModels.*;import com.iiop.ai.mapper.AiDiagnosisMapper;import com.iiop.ai.workflow.*;import com.iiop.common.api.*;import com.iiop.common.exception.BizException;import java.time.LocalDateTime;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class AiDiagnosisService {
 private static final Set<String>TYPES=Set.of("INSPECTION_ABNORMAL","ALARM","MANUAL");private final AiDiagnosisMapper diagnoses;private final AiPersistenceService persistence;private final AiWorkflow workflow;private final ObjectMapper json;private final InspectionClient inspection;private final MaintenanceClient maintenance;private final AiWorkflowEventPublisher events;
 public AiDiagnosisService(AiDiagnosisMapper d,AiPersistenceService p,AiWorkflow w,ObjectMapper j,InspectionClient i,MaintenanceClient m,AiWorkflowEventPublisher e){diagnoses=d;persistence=p;workflow=w;json=j;inspection=i;maintenance=m;events=e;}
 public DiagnosisView create(CreateRequest r){validateRequest(r);validateTrigger(r);if(!"MANUAL".equals(r.triggerType())&&diagnoses.selectCount(Wrappers.<Diagnosis>lambdaQuery().eq(Diagnosis::getTriggerType,r.triggerType()).eq(Diagnosis::getTriggerId,r.triggerId()))>0)throw conflict("该触发对象已存在诊断");Diagnosis d=new Diagnosis();d.setDiagnosisCode("AI"+System.currentTimeMillis());d.setTriggerType(r.triggerType());d.setTriggerId(r.triggerId());d.setDeviceId(r.deviceId());d.setAbnormalSummary(blank(r.abnormalSummary())?"待加载异常摘要":r.abnormalSummary());d.setUserDescription(r.userDescription());d.setDiagnosisStatus("PENDING");d.setConfirmationStatus("PENDING");d.setPromptVersion("iiop-diagnosis-v1");d.setCreatedAt(LocalDateTime.now());persistence.create(d);events.begin(d.getId(),StpUtil.getLoginIdAsLong());events.publish(d.getId(),"PENDING",null,null,"诊断任务已创建");persistence.markRunning(d.getId());try{WorkflowData result=workflow.execute(d,new WorkflowInput(r.triggerType(),r.triggerId(),r.deviceId(),r.abnormalSummary(),r.userDescription()));applySuccess(d,result);persistence.finish(d);return view(d);}catch(Exception e){return view(require(d.getId()));}finally{events.end(d.getId());}}
 public PageResult<Diagnosis> list(long page,long size,String triggerType,Long triggerId,Long deviceId,String diagnosisStatus,String riskLevel,String confirmationStatus){var q=Wrappers.<Diagnosis>lambdaQuery().eq(triggerType!=null,Diagnosis::getTriggerType,triggerType).eq(triggerId!=null,Diagnosis::getTriggerId,triggerId).eq(deviceId!=null,Diagnosis::getDeviceId,deviceId).eq(diagnosisStatus!=null,Diagnosis::getDiagnosisStatus,diagnosisStatus).eq(riskLevel!=null,Diagnosis::getRiskLevel,riskLevel).eq(confirmationStatus!=null,Diagnosis::getConfirmationStatus,confirmationStatus);var p=diagnoses.selectPage(new com.baomidou.mybatisplus.extension.plugins.pagination.Page<Diagnosis>(page,Math.min(size,100)),q.orderByDesc(Diagnosis::getCreatedAt));return new PageResult<>(p.getCurrent(),p.getSize(),p.getTotal(),p.getRecords());}
 public DiagnosisView detail(Long id){return view(require(id));}public List<WorkflowTraceView> workflow(Long id){require(id);return persistence.traces(id).stream().map(this::traceView).toList();}public DiagnosisSummary summary(Long id){Diagnosis d=require(id);return new DiagnosisSummary(d.getId(),d.getTriggerType(),d.getTriggerId(),d.getDeviceId(),d.getDiagnosisStatus(),d.getConfirmationStatus(),d.getRiskLevel());}
 @Transactional public DiagnosisView confirm(Long id,String comment,boolean accepted){require(id);if(!accepted&&blank(comment))throw bad("拒绝原因必填");int n=diagnoses.update(null,Wrappers.<Diagnosis>lambdaUpdate().eq(Diagnosis::getId,id).eq(Diagnosis::getDiagnosisStatus,"SUCCEEDED").eq(Diagnosis::getConfirmationStatus,"PENDING").set(Diagnosis::getConfirmationStatus,accepted?"CONFIRMED":"REJECTED").set(Diagnosis::getConfirmedBy,StpUtil.getLoginIdAsLong()).set(Diagnosis::getConfirmedAt,LocalDateTime.now()).set(Diagnosis::getConfirmationComment,comment));if(n!=1)throw conflict("诊断状态已变化");return view(require(id));}
 private void validateRequest(CreateRequest r){if(!TYPES.contains(r.triggerType()))throw bad("触发类型不正确");if(r.deviceId()==null)throw bad("deviceId 必填");if("MANUAL".equals(r.triggerType())){if(r.triggerId()!=null||blank(r.abnormalSummary()))throw bad("MANUAL 诊断需要异常摘要且不能传 triggerId");}else if(r.triggerId()==null)throw bad("非 MANUAL 诊断需要 triggerId");}
 private boolean pureInspector(){return StpUtil.hasRole("INSPECTOR")&&!StpUtil.hasRole("ADMIN")&&!StpUtil.hasRole("SUPER_ADMIN")&&!StpUtil.hasRole("MAINTAINER");}private void validateTrigger(CreateRequest r){if(pureInspector()&&!"INSPECTION_ABNORMAL".equals(r.triggerType()))throw forbidden("巡检员只能诊断本人巡检异常");if("MANUAL".equals(r.triggerType()))return;if("INSPECTION_ABNORMAL".equals(r.triggerType())){AbnormalDto a=abnormal(r.triggerId());if(!Objects.equals(a.deviceId(),r.deviceId()))throw bad("触发对象与设备不匹配");if(pureInspector()&&!Objects.equals(a.assigneeUserId(),StpUtil.getLoginIdAsLong()))throw forbidden("只能诊断本人巡检异常");return;}AlarmDto a=alarm(r.triggerId());if(!Objects.equals(a.deviceId(),r.deviceId()))throw bad("触发对象与设备不匹配");}
 private AbnormalDto abnormal(Long id){try{Result<AbnormalDto>r=inspection.abnormal(id);if(r==null||r.code()!=0||r.data()==null)throw new BizException(ErrorCode.NOT_FOUND,"巡检异常不存在");return r.data();}catch(BizException e){throw e;}catch(FeignException.NotFound e){throw new BizException(ErrorCode.NOT_FOUND,"巡检异常不存在");}catch(FeignException e){throw new BizException(ErrorCode.SERVICE_UNAVAILABLE,"巡检服务不可用");}}private AlarmDto alarm(Long id){try{Result<AlarmDto>r=maintenance.alarm(id);if(r==null||r.code()!=0||r.data()==null)throw new BizException(ErrorCode.NOT_FOUND,"告警不存在");return r.data();}catch(BizException e){throw e;}catch(FeignException.NotFound e){throw new BizException(ErrorCode.NOT_FOUND,"告警不存在");}catch(FeignException e){throw new BizException(ErrorCode.SERVICE_UNAVAILABLE,"维修服务不可用");}}
 private void applySuccess(Diagnosis d,WorkflowData r){ModelResult m=r.model;d.setRiskLevel(r.risk);d.setAbnormalSummary(m.abnormalSummary());d.setPossibleCauses(m.possibleCauses());d.setInvestigationSteps(m.investigationSteps());d.setMaintenanceAdvice(m.maintenanceAdvice());d.setSafetyNotice(m.safetyNotice());d.setContextSnapshot(r.context);d.setModelName(workflow.modelName());d.setDiagnosisStatus("SUCCEEDED");d.setConfirmationStatus("PENDING");d.setErrorMessage(null);}private Diagnosis require(Long id){Diagnosis d=diagnoses.selectById(id);if(d==null)throw new BizException(ErrorCode.NOT_FOUND,"AI 诊断不存在");return d;}
 private DiagnosisView view(Diagnosis d){WorkOrderDraft draft=null;for(WorkflowTrace t:persistence.traces(d.getId()))if("PREPARE_WORK_ORDER_DRAFT".equals(t.getNodeCode())&&"SUCCEEDED".equals(t.getNodeStatus())&&t.getOutputData()!=null)try{draft=json.readValue(t.getOutputData(),WorkOrderDraft.class);}catch(Exception ignored){}return new DiagnosisView(d,d.getPossibleCauses()==null?List.of():d.getPossibleCauses(),d.getInvestigationSteps()==null?List.of():d.getInvestigationSteps(),draft,AiWorkflow.requiresConfirmation(d.getRiskLevel()));}private boolean blank(String v){return v==null||v.isBlank();}private BizException bad(String m){return new BizException(ErrorCode.BAD_REQUEST,m);}private BizException conflict(String m){return new BizException(ErrorCode.CONFLICT,m);}private BizException forbidden(String m){return new BizException(ErrorCode.FORBIDDEN,m);}
 private WorkflowTraceView traceView(WorkflowTrace t){Long duration=null;if(t.getStartedAt()!=null){LocalDateTime end=t.getFinishedAt()==null?LocalDateTime.now():t.getFinishedAt();duration=java.time.Duration.between(t.getStartedAt(),end).toMillis();}String message=t.getErrorMessage()!=null?t.getErrorMessage():switch(t.getNodeStatus()){case "PENDING"->"等待执行";case "RUNNING"->"正在执行";case "SUCCEEDED"->summary(t.getOutputData());case "SKIPPED"->"因前序节点失败而跳过";default->"执行失败";};return new WorkflowTraceView(t.getId(),t.getNodeCode(),t.getNodeName(),t.getNodeStatus(),t.getStartedAt(),t.getFinishedAt(),duration,message,t.getErrorMessage());}
 private String summary(String output){if(blank(output))return "执行完成";try{var n=json.readTree(output);if(n.has("finalRisk"))return "AI 辅助风险等级："+n.get("finalRisk").asText();if(n.has("modelRisk"))return "DeepSeek 已返回结构化分析，风险建议："+n.get("modelRisk").asText();if(n.has("maintenanceAdvice"))return "已生成维修建议与安全注意事项";if(n.has("title"))return "已生成待人工审核的工单草稿";if(n.has("device"))return "已加载设备、巡检与维修上下文";}catch(Exception ignored){}return "执行完成";}
}
