<script setup lang="ts">
import {computed,onMounted} from 'vue';
import {useAuthStore} from '../stores/auth';
import {useRoute,useRouter} from 'vue-router';
import {displayValue} from '../utils/display';
const s=useAuthStore(),r=useRouter(),route=useRoute();
const menus:Array<[string,string,string,string[]]>=[['/dashboard','工作台','dashboard:view',['SUPER_ADMIN','ADMIN']],['/devices','设备管理','device:view',['SUPER_ADMIN','ADMIN','INSPECTOR','MAINTAINER']],['/inspection/templates','巡检模板','inspection:view',['SUPER_ADMIN','ADMIN']],['/inspection/plans','巡检计划','inspection:view',['SUPER_ADMIN','ADMIN']],['/inspection/tasks','巡检任务','inspection:view',['SUPER_ADMIN','ADMIN','INSPECTOR']],['/inspection/abnormals','巡检异常','inspection:view',['SUPER_ADMIN','ADMIN','INSPECTOR']],['/maintenance/defects','维修缺陷','maintenance:view',['SUPER_ADMIN','ADMIN','MAINTAINER']],['/maintenance/work-orders','维修工单','maintenance:view',['SUPER_ADMIN','ADMIN','MAINTAINER']],['/ai/diagnoses','AI诊断','ai:view',['SUPER_ADMIN','ADMIN','INSPECTOR','MAINTAINER']],['/system/users','用户管理','system:user:view',['SUPER_ADMIN','ADMIN']],['/system/roles','角色查看','system:role:view',['SUPER_ADMIN','ADMIN']],['/system/permissions','权限查看','system:permission:view',['SUPER_ADMIN','ADMIN']],['/notifications','通知中心','',['SUPER_ADMIN','ADMIN','INSPECTOR','MAINTAINER']]];
const visibleMenus=computed(()=>menus.filter(m=>m[3].some((role:string)=>s.roles.includes(role))&&(!m[2]||s.can(m[2]))));
onMounted(()=>s.refreshUnread()); async function out(){await s.logout();r.push('/login')}
</script>
<template><el-container class="shell"><el-aside width="220px"><h2>IIOP</h2><p>工业设备智能巡检</p><el-menu router :default-active="route.path"><el-menu-item v-for="m in visibleMenus" :key="m[0]" :index="m[0]">{{m[1]}}</el-menu-item></el-menu></el-aside><el-container><el-header><el-breadcrumb><el-breadcrumb-item>首页</el-breadcrumb-item><el-breadcrumb-item>{{route.meta.title}}</el-breadcrumb-item></el-breadcrumb><span><el-button link @click="r.push('/notifications')">通知 <el-badge :value="s.unread" :hidden="!s.unread"/></el-button>{{s.currentUser?.username||'当前用户'}}（{{displayValue(s.roles[0])}}） <el-button link @click="out">退出</el-button></span></el-header><el-main><RouterView/></el-main></el-container></el-container></template>
