package com.iiop.maintenance.service;

import cn.dev33.satoken.stp.StpUtil;import com.baomidou.mybatisplus.core.metadata.IPage;import com.baomidou.mybatisplus.core.toolkit.Wrappers;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import com.iiop.common.api.*;import com.iiop.common.exception.BizException;import com.iiop.common.mq.InspectionAbnormalEvent;import com.iiop.maintenance.client.AuthClient;import com.iiop.maintenance.client.AuthClient.NotificationRequest;import com.iiop.maintenance.domain.MaintenanceDtos.*;import com.iiop.maintenance.domain.MaintenanceModels.*;import com.iiop.maintenance.mapper.*;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;import org.slf4j.*;import org.springframework.dao.DuplicateKeyException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;

@Service public class MaintenanceService {
 private static final Logger log=LoggerFactory.getLogger(MaintenanceService.class);private final AlarmMapper alarms;private final DefectMapper defects;private final WorkOrderMapper orders;private final WorkOrderLogMapper logs;private final MaintenanceRecordMapper records;private final AcceptanceMapper acceptances;private final AuthClient auth;
 public MaintenanceService(AlarmMapper a,DefectMapper d,WorkOrderMapper o,WorkOrderLogMapper l,MaintenanceRecordMapper r,AcceptanceMapper ac,AuthClient auth){alarms=a;defects=d;orders=o;logs=l;records=r;acceptances=ac;this.auth=auth;}
 @Transactional public void consumeAbnormal(InspectionAbnormalEvent e){if(e==null||e.abnormalId()==null)return;if(defects.selectCount(Wrappers.<Defect>lambdaQuery().eq(Defect::getSourceType,"INSPECTION_ABNORMAL").eq(Defect::getSourceId,e.abnormalId()))>0)return;Defect d=new Defect();d.setDefectCode(code("DEF"));d.setDeviceId(e.deviceId());d.setSourceType("INSPECTION_ABNORMAL");d.setSourceId(e.abnormalId());d.setTitle(e.title());d.setDescription("巡检异常自动生成缺陷");d.setSeverity(e.severity());d.setReportedAt(e.occurredAt());d.setStatus("OPEN");try{defects.insert(d);}catch(DuplicateKeyException duplicate){log.info("忽略重复巡检异常消息 abnormalId={}",e.abnormalId());}}
 public PageResult<Alarm> alarms(long p,long s){IPage<Alarm> page=alarms.selectPage(new Page<>(p,Math.min(s,100)),Wrappers.<Alarm>lambdaQuery().orderByDesc(Alarm::getOccurTime));return page(page);}public Alarm alarm(Long id){Alarm v=alarms.selectById(id);if(v==null)throw notFound("告警不存在");return v;}
 @Transactional public Alarm alarmStatus(Long id,String action){Alarm a=alarm(id);if("acknowledge".equals(action)){if(!"ACTIVE".equals(a.getStatus()))throw conflict("只有活动告警可以确认");a.setStatus("ACKNOWLEDGED");}else if("close".equals(action)){if(!Set.of("ACTIVE","ACKNOWLEDGED","RECOVERED").contains(a.getStatus()))throw conflict("告警不能关闭");a.setStatus("CLOSED");}else throw bad("告警操作不正确");alarms.updateById(a);return a;}
 public PageResult<Defect> defects(long p,long s){IPage<Defect> page=defects.selectPage(new Page<>(p,Math.min(s,100)),Wrappers.<Defect>lambdaQuery().orderByDesc(Defect::getReportedAt));return page(page);}public Defect defect(Long id){Defect v=defects.selectById(id);if(v==null)throw notFound("缺陷不存在");return v;}
 @Transactional public Defect defectStatus(Long id,StatusRequest request){if(!Set.of("OPEN","CONFIRMED","PROCESSING","RESOLVED","CLOSED").contains(request.status()))throw bad("缺陷状态不正确");Defect d=defect(id);d.setStatus(request.status());if("RESOLVED".equals(request.status())||"CLOSED".equals(request.status()))d.setResolvedAt(LocalDateTime.now());defects.updateById(d);return d;}
 public PageResult<WorkOrder> orders(long p,long s,String status){IPage<WorkOrder> page=orders.selectPage(new Page<>(p,Math.min(s,100)),Wrappers.<WorkOrder>lambdaQuery().eq(status!=null,WorkOrder::getStatus,status).orderByDesc(WorkOrder::getCreatedAt));return page(page);}public WorkOrder order(Long id){WorkOrder v=orders.selectById(id);if(v==null)throw notFound("工单不存在");return v;}
 public WorkOrderDetail detail(Long id){return new WorkOrderDetail(order(id),logs.selectList(Wrappers.<WorkOrderLog>lambdaQuery().eq(WorkOrderLog::getWorkOrderId,id).orderByAsc(WorkOrderLog::getCreatedAt)),records.selectList(Wrappers.<MaintenanceRecord>lambdaQuery().eq(MaintenanceRecord::getWorkOrderId,id)),acceptances.selectList(Wrappers.<Acceptance>lambdaQuery().eq(Acceptance::getWorkOrderId,id).orderByAsc(Acceptance::getAcceptedAt)));}
 @Transactional public WorkOrder create(WorkOrder v){Defect linkedDefect=null;if(v.getDefectId()!=null){linkedDefect=defect(v.getDefectId());if(v.getDeviceId()==null)v.setDeviceId(linkedDefect.getDeviceId());else if(!v.getDeviceId().equals(linkedDefect.getDeviceId()))throw bad("工单设备必须与缺陷设备一致");if(v.getAiDiagnosisId()==null)v.setAiDiagnosisId(linkedDefect.getAiDiagnosisId());}else if(v.getDeviceId()==null)throw bad("工单必须填写设备");if(!Set.of("REPAIR","PREVENTIVE","EMERGENCY").contains(v.getWorkOrderType())||!Set.of("LOW","MEDIUM","HIGH","URGENT").contains(v.getPriority()))throw bad("工单类型或优先级不正确");v.setWorkOrderCode(code("WO"));v.setCreatorUserId(StpUtil.getLoginIdAsLong());v.setStatus("PENDING");orders.insert(v);writeLog(v.getId(),"CREATE","DRAFT","PENDING",v.getCreatorUserId(),"创建并提交工单");return v;}
 @Transactional public WorkOrder assign(Long id,AssignRequest request){WorkOrder o=order(id);if(!"PENDING".equals(o.getStatus()))throw conflict("工单不是待分派状态");o.setAssigneeUserId(request.assigneeUserId());transition(o,"ASSIGN","ASSIGNED",request.comment());Result<Object> result=auth.notify(new NotificationRequest(request.assigneeUserId(),"WORK_ORDER","新维修工单",o.getTitle(),"WORK_ORDER",o.getId()));if(result==null||result.code()!=0)throw new BizException(ErrorCode.SERVICE_UNAVAILABLE,"工单通知创建失败");return o;}
 @Transactional public WorkOrder start(Long id,String comment){WorkOrder o=order(id);if(!"ASSIGNED".equals(o.getStatus()))throw conflict("工单不是已分派状态");o.setActualStartTime(LocalDateTime.now());transition(o,"START","PROCESSING",comment);return o;}
 @Transactional public WorkOrder repair(Long id,RepairRequest request){WorkOrder o=order(id);if(!"PROCESSING".equals(o.getStatus()))throw conflict("工单不是处理中状态");if(!Set.of("SUCCESS","PARTIAL","FAILED").contains(request.result()))throw bad("维修结果不正确");MaintenanceRecord r=new MaintenanceRecord();r.setWorkOrderId(id);r.setDeviceId(o.getDeviceId());r.setFaultCause(request.faultCause());r.setSolution(request.solution());r.setPartsUsed(request.partsUsed());r.setDowntimeMinutes(request.downtimeMinutes());r.setMaintenanceCost(request.maintenanceCost());r.setResult(request.result());r.setRepairedBy(StpUtil.getLoginIdAsLong());r.setRepairedAt(LocalDateTime.now());records.insert(r);transition(o,"SUBMIT_REPAIR","WAITING_ACCEPTANCE",request.comment());return o;}
 @Transactional public WorkOrder accept(Long id,AcceptanceRequest request){WorkOrder o=order(id);if(!"WAITING_ACCEPTANCE".equals(o.getStatus()))throw conflict("工单不是待验收状态");if(!Set.of("PASSED","REJECTED").contains(request.acceptanceResult()))throw bad("验收结果不正确");Acceptance a=new Acceptance();a.setWorkOrderId(id);a.setDeviceId(o.getDeviceId());a.setAcceptanceResult(request.acceptanceResult());a.setAcceptanceContent(request.acceptanceContent());a.setAcceptedBy(StpUtil.getLoginIdAsLong());a.setAcceptedAt(LocalDateTime.now());acceptances.insert(a);if("PASSED".equals(request.acceptanceResult())){o.setActualEndTime(LocalDateTime.now());o.setCloseResult(request.acceptanceContent());transition(o,"ACCEPT","COMPLETED",request.comment());if(o.getDefectId()!=null){Defect d=defect(o.getDefectId());d.setStatus("RESOLVED");d.setResolvedAt(LocalDateTime.now());defects.updateById(d);}}else transition(o,"REJECT","PROCESSING",request.comment());return o;}
 public MaintenanceHistory history(Long deviceId){return new MaintenanceHistory(deviceId,orders.selectList(Wrappers.<WorkOrder>lambdaQuery().eq(WorkOrder::getDeviceId,deviceId).orderByDesc(WorkOrder::getCreatedAt).last("LIMIT 20")),records.selectList(Wrappers.<MaintenanceRecord>lambdaQuery().eq(MaintenanceRecord::getDeviceId,deviceId).orderByDesc(MaintenanceRecord::getRepairedAt).last("LIMIT 20")),acceptances.selectList(Wrappers.<Acceptance>lambdaQuery().eq(Acceptance::getDeviceId,deviceId).orderByDesc(Acceptance::getAcceptedAt).last("LIMIT 20")));}
 private void transition(WorkOrder o,String action,String to,String comment){String from=o.getStatus();o.setStatus(to);orders.updateById(o);writeLog(o.getId(),action,from,to,StpUtil.getLoginIdAsLong(),comment);}private void writeLog(Long id,String action,String from,String to,Long user,String comment){WorkOrderLog l=new WorkOrderLog();l.setWorkOrderId(id);l.setAction(action);l.setFromStatus(from);l.setToStatus(to);l.setOperatorUserId(user);l.setComment(comment);logs.insert(l);}
 private static String code(String p){return p+LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMddHHmmssSSS"))+UUID.randomUUID().toString().substring(0,4).toUpperCase();}private static BizException bad(String m){return new BizException(ErrorCode.BAD_REQUEST,m);}private static BizException conflict(String m){return new BizException(ErrorCode.CONFLICT,m);}private static BizException notFound(String m){return new BizException(ErrorCode.NOT_FOUND,m);}private static <T> PageResult<T> page(IPage<T> p){return new PageResult<>(p.getCurrent(),p.getSize(),p.getTotal(),p.getRecords());}
}
