-- IIOP M1: 创建五个逻辑数据库
CREATE DATABASE IF NOT EXISTS iiop_auth
    CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS iiop_device
    CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS iiop_inspection
    CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS iiop_maintenance
    CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS iiop_ai
    CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
