-- IIOP M1: iiop_inspection 数据库表结构
USE iiop_inspection;

CREATE TABLE IF NOT EXISTS ins_template (
    id BIGINT NOT NULL COMMENT '主键',
    template_code VARCHAR(64) NOT NULL COMMENT '模板编码',
    template_name VARCHAR(128) NOT NULL COMMENT '模板名称',
    category_id BIGINT NULL COMMENT '设备分类ID',
    version INT NOT NULL DEFAULT 1 COMMENT '版本',
    description VARCHAR(500) NULL COMMENT '描述',
    flow_definition JSON NULL COMMENT 'Vue Flow流程JSON',
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/ENABLED/DISABLED',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0正常，1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_ins_template_code (template_code),
    KEY idx_ins_template_category (category_id),
    KEY idx_ins_template_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='巡检模板';

CREATE TABLE IF NOT EXISTS ins_template_item (
    id BIGINT NOT NULL COMMENT '主键',
    template_id BIGINT NOT NULL COMMENT '模板ID',
    item_code VARCHAR(64) NOT NULL COMMENT '检查项编码',
    item_name VARCHAR(128) NOT NULL COMMENT '检查项名称',
    item_type VARCHAR(32) NOT NULL COMMENT 'NUMBER/BOOLEAN/TEXT/PHOTO',
    unit VARCHAR(32) NULL COMMENT '单位',
    standard_value VARCHAR(255) NULL COMMENT '标准值',
    lower_limit DECIMAL(18,6) NULL COMMENT '下限',
    upper_limit DECIMAL(18,6) NULL COMMENT '上限',
    required_flag TINYINT NOT NULL DEFAULT 1 COMMENT '是否必填',
    sort_order INT NOT NULL DEFAULT 0 COMMENT '排序',
    inspection_method VARCHAR(500) NULL COMMENT '检查方法',
    abnormal_hint VARCHAR(500) NULL COMMENT '异常提示',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0正常，1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_ins_template_item_code (template_id, item_code),
    KEY idx_ins_template_item_order (template_id, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='巡检模板项';

CREATE TABLE IF NOT EXISTS ins_plan (
    id BIGINT NOT NULL COMMENT '主键',
    plan_code VARCHAR(64) NOT NULL COMMENT '计划编码',
    plan_name VARCHAR(128) NOT NULL COMMENT '计划名称',
    device_id BIGINT NOT NULL COMMENT '设备ID',
    template_id BIGINT NOT NULL COMMENT '模板ID',
    schedule_type VARCHAR(32) NOT NULL COMMENT 'DAILY/WEEKLY/MONTHLY/CRON',
    cron_expression VARCHAR(128) NULL COMMENT 'Cron表达式',
    start_date DATE NOT NULL COMMENT '开始日期',
    end_date DATE NULL COMMENT '结束日期',
    assignee_user_id BIGINT NOT NULL COMMENT '执行人用户ID',
    status VARCHAR(32) NOT NULL COMMENT 'ENABLED/DISABLED',
    last_generate_time DATETIME NULL COMMENT '最近生成时间',
    next_generate_time DATETIME NULL COMMENT '下次生成时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0正常，1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_ins_plan_code (plan_code),
    KEY idx_ins_plan_device (device_id),
    KEY idx_ins_plan_template (template_id),
    KEY idx_ins_plan_assignee (assignee_user_id),
    KEY idx_ins_plan_status_next (status, next_generate_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='巡检计划';

CREATE TABLE IF NOT EXISTS ins_task (
    id BIGINT NOT NULL COMMENT '主键',
    task_code VARCHAR(64) NOT NULL COMMENT '任务编码',
    plan_id BIGINT NULL COMMENT '计划ID',
    device_id BIGINT NOT NULL COMMENT '设备ID',
    template_id BIGINT NOT NULL COMMENT '模板ID',
    assignee_user_id BIGINT NOT NULL COMMENT '执行人用户ID',
    task_status VARCHAR(32) NOT NULL COMMENT 'PENDING/IN_PROGRESS/COMPLETED/CANCELLED',
    overdue_flag TINYINT NOT NULL DEFAULT 0 COMMENT '是否逾期',
    result_status VARCHAR(32) NOT NULL COMMENT 'UNKNOWN/NORMAL/ABNORMAL',
    scheduled_start_time DATETIME NOT NULL COMMENT '计划开始时间',
    scheduled_end_time DATETIME NULL COMMENT '计划结束时间',
    actual_start_time DATETIME NULL COMMENT '实际开始时间',
    actual_end_time DATETIME NULL COMMENT '实际结束时间',
    completion_rate DECIMAL(5,2) NOT NULL DEFAULT 0 COMMENT '完成率',
    remark VARCHAR(1000) NULL COMMENT '备注',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_ins_task_code (task_code),
    KEY idx_ins_task_plan (plan_id),
    KEY idx_ins_task_device_time (device_id, scheduled_start_time),
    KEY idx_ins_task_assignee_status (assignee_user_id, task_status),
    KEY idx_ins_task_status_time (task_status, scheduled_start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='巡检任务';

CREATE TABLE IF NOT EXISTS ins_task_item (
    id BIGINT NOT NULL COMMENT '主键',
    task_id BIGINT NOT NULL COMMENT '任务ID',
    template_item_id BIGINT NULL COMMENT '模板项ID',
    item_code VARCHAR(64) NOT NULL COMMENT '检查项编码快照',
    item_name VARCHAR(128) NOT NULL COMMENT '检查项名称快照',
    item_type VARCHAR(32) NOT NULL COMMENT '检查项类型快照',
    unit VARCHAR(32) NULL COMMENT '单位快照',
    standard_value VARCHAR(255) NULL COMMENT '标准值快照',
    lower_limit DECIMAL(18,6) NULL COMMENT '下限快照',
    upper_limit DECIMAL(18,6) NULL COMMENT '上限快照',
    required_flag TINYINT NOT NULL DEFAULT 1 COMMENT '是否必填',
    inspection_method VARCHAR(500) NULL COMMENT '检查方法快照',
    actual_value TEXT NULL COMMENT '实际值',
    result_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/NORMAL/ABNORMAL',
    remark VARCHAR(1000) NULL COMMENT '备注',
    evidence_urls JSON NULL COMMENT '证据URL列表',
    sort_order INT NOT NULL DEFAULT 0 COMMENT '排序',
    checked_at DATETIME NULL COMMENT '检查时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_ins_task_item_code (task_id, item_code),
    KEY idx_ins_task_item_order (task_id, sort_order),
    KEY idx_ins_task_item_result (result_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='巡检任务项';

CREATE TABLE IF NOT EXISTS ins_abnormal (
    id BIGINT NOT NULL COMMENT '主键',
    abnormal_code VARCHAR(64) NOT NULL COMMENT '异常编码',
    task_id BIGINT NOT NULL COMMENT '任务ID',
    task_item_id BIGINT NULL COMMENT '任务项ID',
    device_id BIGINT NOT NULL COMMENT '设备ID',
    abnormal_type VARCHAR(64) NOT NULL COMMENT '异常类型',
    severity VARCHAR(32) NOT NULL COMMENT 'LOW/MEDIUM/HIGH/CRITICAL',
    title VARCHAR(128) NOT NULL COMMENT '标题',
    description VARCHAR(2000) NOT NULL COMMENT '描述',
    evidence_urls JSON NULL COMMENT '证据URL列表',
    reported_by BIGINT NOT NULL COMMENT '上报人用户ID',
    reported_at DATETIME NOT NULL COMMENT '上报时间',
    status VARCHAR(32) NOT NULL COMMENT 'OPEN/PROCESSING/RESOLVED/CLOSED',
    ai_diagnosis_id BIGINT NULL COMMENT 'AI诊断ID',
    resolved_at DATETIME NULL COMMENT '解决时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_ins_abnormal_code (abnormal_code),
    KEY idx_ins_abnormal_task (task_id),
    KEY idx_ins_abnormal_device_time (device_id, reported_at),
    KEY idx_ins_abnormal_severity_status (severity, status),
    KEY idx_ins_abnormal_reporter_time (reported_by, reported_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='巡检异常';
